name: akasha
version: 0.6.0
summary: AKASHA
description: Akasha platform
confinement: strict
grade: devel
icon: gui/icon.png
apps:
  akasha:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/akasha
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
    source: linux-unpacked
    after:
      - desktop-gtk2
