export const SHOW_ERROR = 'SHOW_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SHOW_PANEL = 'SHOW_PANEL';
export const HIDE_PANEL = 'HIDE_PANEL';
export const CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES';
export const SHOW_AUTH_DIALOG = 'SHOW_AUTH_DIALOG';
export const HIDE_AUTH_DIALOG = 'HIDE_AUTH_DIALOG';
export const SHOW_ENTRY_MODAL = 'SHOW_ENTRY_MODAL';
export const HIDE_ENTRY_MODAL = 'HIDE_ENTRY_MODAL';
export const CAST_UPVOTE_ERROR = 'CAST_UPVOTE_ERROR';
export const CAST_UPVOTE_SUCCESS = 'CAST_UPVOTE_SUCCESS';
export const SET_TIMESTAMP = 'SET_TIMESTAMP';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const SHOW_PUBLISH_CONFIRM_DIALOG = 'SHOW_PUBLISH_CONFIRM_DIALOG';
export const HIDE_PUBLISH_CONFIRM_DIALOG = 'HIDE_PUBLISH_CONFIRM_DIALOG';

export const SHOW_WEIGHT_CONFIRM_DIALOG = 'SHOW_WEIGHT_CONFIRM_DIALOG';
export const HIDE_WEIGHT_CONFIRM_DIALOG = 'HIDE_WEIGHT_CONFIRM_DIALOG';

export const ADD_PENDING_ACTION = 'ADD_PENDING_ACTION';
export const UPDATE_PENDING_ACTION = 'UPDATE_PENDING_ACTION';
export const DELETE_PENDING_ACTION = 'DELETE_PENDING_ACTION';

export const SHOW_TERMS = 'SHOW_TERMS';
export const HIDE_TERMS = 'HIDE_TERMS';

export const CLEAN_STORE = 'CLEAN_STORE';
