export const SHOW_ERROR = 'SHOW_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SHOW_PANEL = 'SHOW_PANEL';
export const HIDE_PANEL = 'HIDE_PANEL';
export const CHECK_FOR_UPDATES = 'CHECK_FOR_UPDATES';
export const SHOW_AUTH_DIALOG = 'SHOW_AUTH_DIALOG';
export const HIDE_AUTH_DIALOG = 'HIDE_AUTH_DIALOG';
