export const GET_CURRENT_CHANNELS_SUCCESS = 'GET_CURRENT_CHANNELS_SUCCESS';
export const GET_CURRENT_CHANNELS_ERROR = 'GET_CURRENT_CHANNELS_ERROR';

export const GET_JOINED_CHANNELS_SUCCESS = 'GET_JOINED_CHANNELS_SUCCESS';
export const GET_JOINED_CHANNELS_ERROR = 'GET_JOINED_CHANNELS_ERROR';

export const GET_RECENT_CHANNELS_SUCCESS = 'GET_RECENT_CHANNELS_SUCCESS';
export const GET_RECENT_CHANNELS_ERROR = 'GET_RECENT_CHANNELS_ERROR';

export const SAVE_CHANNEL_SUCCESS = 'SAVE_CHANNEL_SUCCESS';
export const SAVE_CHANNEL_ERROR = 'SAVE_CHANNEL_ERROR';

export const DELETE_CHANNEL_SUCCESS = 'DELETE_CHANNEL_SUCCESS';
export const DELETE_CHANNEL_ERROR = 'DELETE_CHANNEL_ERROR';

export const SAVE_RECENT_CHANNEL_SUCCESS = 'SAVE_RECENT_CHANNEL_SUCCESS';
export const SAVE_RECENT_CHANNEL_ERROR = 'SAVE_RECENT_CHANNEL_ERROR';

export const DELETE_RECENT_CHANNEL_SUCCESS = 'DELETE_RECENT_CHANNEL_SUCCESS';
export const DELETE_RECENT_CHANNEL_ERROR = 'DELETE_RECENT_CHANNEL_ERROR';

export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL';
