export const GET_ENTRY_COMMENTS = 'GET_ENTRY_COMMENTS';
export const GET_ENTRY_COMMENTS_SUCCESS = 'GET_ENTRY_COMMENTS_SUCCESS';
export const GET_ENTRY_COMMENTS_ERROR = 'GET_ENTRY_COMMENTS_ERROR';

export const PUBLISH_COMMENT = 'PUBLISH_COMMENT';
export const PUBLISH_COMMENT_SUCCESS = 'PUBLISH_COMMENT_SUCCESS';
export const PUBLISH_COMMENT_OPTIMISTIC = 'PUBLISH_COMMENT_OPTIMISTIC';
export const PUBLISH_COMMENT_ERROR = 'PUBLISH_COMMENT_ERROR';

export const UNLOAD_COMMENTS = 'UNLOAD_COMMENTS';
