export const SAVE_DRAFT = 'SAVE_DRAFT';
export const CREATE_DRAFT_SUCCESS = 'CREATE_DRAFT_SUCCESS';
export const CREATE_DRAFT_ERROR = 'CREATE_DRAFT_ERROR';

export const UPDATE_DRAFT_SUCCESS = 'UPDATE_DRAFT_SUCCESS';
export const UPDATE_DRAFT_ERROR = 'UPDATE_DRAFT_ERROR';

export const DELETE_DRAFT_SUCCESS = 'DELETE_DRAFT_SUCCESS';
export const DELETE_DRAFT_ERROR = 'DELETE_DRAFT_ERROR';

export const GET_DRAFTS_SUCCESS = 'GET_DRAFTS_SUCCESS';
export const GET_DRAFTS_ERROR = 'GET_DRAFTS_ERROR';

export const GET_DRAFT_SUCCESS = 'GET_DRAFT_SUCCESS';
export const GET_DRAFT_ERROR = 'GET_DRAFT_ERROR';

export const GET_DRAFTS_COUNT = 'GET_DRAFTS_COUNT';
export const GET_DRAFTS_COUNT_SUCCESS = 'GET_DRAFTS_COUNT_SUCCESS';
export const GET_DRAFTS_COUNT_ERROR = 'GET_DRAFTS_COUNT_ERROR';

export const GET_DRAFT_BY_ID_SUCCESS = 'GET_DRAFT_BY_ID_SUCCESS';
export const GET_DRAFT_BY_ID_ERROR = 'GET_DRAFT_BY_ID_ERROR';

export const GET_PUBLISHING_DRAFTS = 'GET_PUBLISHING_DRAFTS';
export const GET_PUBLISHING_DRAFTS_SUCCESS = 'GET_PUBLISHING_DRAFTS_SUCCESS';
export const GET_PUBLISHING_DRAFTS_ERROR = 'GET_PUBLISHING_DRAFTS_ERROR';

export const PUBLISH_DRAFT = 'PUBLISH_DRAFT';
export const PUBLISH_DRAFT_SUCCESS = 'PUBLISH_DRAFT_SUCCESS';
export const PUBLISH_DRAFT_ERROR = 'PUBLISH_DRAFT_ERROR';

export const START_PUBLISHING_DRAFT = 'START_PUBLISHING_DRAFT';
export const PAUSE_PUBLISHING_DRAFT = 'PAUSE_PUBLISHING_DRAFT';
