export const SAVE_DRAFT = 'SAVE_DRAFT';
export const CREATE_DRAFT_SUCCESS = 'CREATE_DRAFT_SUCCESS';
export const CREATE_DRAFT_ERROR = 'CREATE_DRAFT_ERROR';

export const UPDATE_DRAFT_SUCCESS = 'UPDATE_DRAFT_SUCCESS';
export const UPDATE_DRAFT_ERROR = 'UPDATE_DRAFT_ERROR';

export const GET_DRAFTS_SUCCESS = 'GET_DRAFTS_SUCCESS';
export const GET_DRAFTS_ERROR = 'GET_DRAFTS_ERROR';

export const GET_DRAFT_SUCCESS = 'GET_DRAFT_SUCCESS';
export const GET_DRAFT_ERROR = 'GET_DRAFT_ERROR';

export const GET_DRAFTS_COUNT_SUCCESS = 'GET_DRAFTS_COUNT_SUCCESS';
export const GET_DRAFTS_COUNT_ERROR = 'GET_DRAFTS_COUNT_ERROR';

export const GET_ENTRIES_COUNT_SUCCESS = 'GET_ENTRIES_COUNT_SUCCESS';
export const GET_ENTRIES_COUNT_ERROR = 'GET_ENTRIES_COUNT_ERROR';

export const CHECK_TAG_EXISTENCE = 'CHECK_TAG_EXISTENCE';
export const CHECK_TAG_EXISTENCE_SUCCESS = 'CHECK_TAG_EXISTENCE_SUCCESS';
export const CHECK_TAG_EXISTENCE_ERROR = 'CHECK_TAG_EXISTENCE_ERROR';

export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_ERROR = 'GET_TAGS_ERROR';
