export const GET_ENTRIES_COUNT = 'GET_ENTRIES_COUNT';
export const GET_ENTRIES_COUNT_SUCCESS = 'GET_ENTRIES_COUNT_SUCCESS';
export const GET_ENTRIES_COUNT_ERROR = 'GET_ENTRIES_COUNT_ERROR';

export const GET_SORTED_ENTRIES = 'GET_SORTED_ENTRIES';

export const CREATE_SAVED_ENTRY_SUCCESS = 'CREATE_SAVED_ENTRY_SUCCESS';
export const CREATE_SAVED_ENTRY_ERROR = 'CREATE_SAVED_ENTRY_ERROR';

export const GET_SAVED_ENTRIES_SUCCESS = 'GET_SAVED_ENTRIES_SUCCESS';
export const GET_SAVED_ENTRIES_ERROR = 'GET_SAVED_ENTRIES_ERROR';

export const GET_LICENCES_SUCCESS = 'GET_LICENCES_SUCCESS';
export const GET_LICENCES_ERROR = 'GET_LICENCES_ERROR';

export const GET_LICENCE_BY_ID_SUCCESS = 'GET_LICENCE_BY_ID_SUCCESS';
export const GET_LICENCE_BY_ID_ERROR = 'GET_LICENCE_BY_ID_ERROR';

export const GET_PROFILE_ENTRIES = 'GET_PROFILE_ENTRIES';
export const GET_PROFILE_ENTRIES_SUCCESS = 'GET_PROFILE_ENTRIES_SUCCESS';
export const GET_PROFILE_ENTRIES_ERROR = 'GET_PROFILE_ENTRIES_ERROR';

export const GET_ENTRIES_STREAM = 'GET_ENTRIES_STREAM';
export const GET_ENTRIES_STREAM_SUCCESS = 'GET_ENTRIES_STREAM_SUCCESS';
export const GET_ENTRIES_STREAM_ERROR = 'GET_ENTRIES_STREAM_ERROR';

export const ENTRY_TAG_ITERATOR = 'ENTRY_TAG_ITERATOR';
export const ENTRY_TAG_ITERATOR_SUCCESS = 'ENTRY_TAG_ITERATOR_SUCCESS';
export const ENTRY_TAG_ITERATOR_ERROR = 'ENTRY_TAG_ITERATOR_ERROR';

export const GET_TAG_ENTRIES_COUNT = 'GET_TAG_ENTRIES_COUNT';
export const GET_TAG_ENTRIES_COUNT_SUCCESS = 'GET_TAG_ENTRIES_COUNT_SUCCESS';
export const GET_TAG_ENTRIES_COUNT_ERROR = 'GET_TAG_ENTRIES_COUNT_ERROR';

export const VOTE_COST = 'VOTE_COST';
export const VOTE_COST_SUCCESS = 'VOTE_COST_SUCCESS';
export const VOTE_COST_ERROR = 'VOTE_COST_ERROR';

export const UPVOTE = 'UPVOTE';
export const UPVOTE_SUCCESS = 'UPVOTE_SUCCESS';
export const UPVOTE_ERROR = 'UPVOTE_ERROR';

export const DOWNVOTE = 'DOWNVOTE';
export const DOWNVOTE_SUCCESS = 'DOWNVOTE_SUCCESS';
export const DOWNVOTE_ERROR = 'DOWNVOTE_ERROR';

export const GET_ENTRY = 'GET_ENTRY';
export const GET_ENTRY_SUCCESS = 'GET_ENTRY_SUCCESS';
export const GET_ENTRY_ERROR = 'GET_ENTRY_ERROR';

export const GET_SCORE = 'GET_SCORE';
export const GET_SCORE_SUCCESS = 'GET_SCORE_SUCCESS';
export const GET_SCORE_ERROR = 'GET_SCORE_ERROR';

export const CLEAR_TAG_ENTRIES = 'CLEAR_TAG_ENTRIES';
