export const GET_ENTRIES_COUNT = 'GET_ENTRIES_COUNT';
export const GET_ENTRIES_COUNT_SUCCESS = 'GET_ENTRIES_COUNT_SUCCESS';
export const GET_ENTRIES_COUNT_ERROR = 'GET_ENTRIES_COUNT_ERROR';

export const GET_SORTED_ENTRIES = 'GET_SORTED_ENTRIES';

export const CREATE_SAVED_ENTRY_SUCCESS = 'CREATE_SAVED_ENTRY_SUCCESS';
export const CREATE_SAVED_ENTRY_ERROR = 'CREATE_SAVED_ENTRY_ERROR';

export const GET_SAVED_ENTRIES_SUCCESS = 'GET_SAVED_ENTRIES_SUCCESS';
export const GET_SAVED_ENTRIES_ERROR = 'GET_SAVED_ENTRIES_ERROR';
