export const ACTION_ADD = 'ACTION_ADD';
export const ACTION_CLEAR_HISTORY = 'ACTION_CLEAR_HISTORY';
export const ACTION_DELETE = 'ACTION_DELETE';
export const ACTION_DELETE_ERROR = 'ACTION_DELETE_ERROR';
export const ACTION_GET_CLAIMABLE = 'ACTION_GET_CLAIMABLE';
export const ACTION_GET_CLAIMABLE_ERROR = 'ACTION_GET_CLAIMABLE_ERROR';
export const ACTION_GET_CLAIMABLE_SUCCESS = 'ACTION_GET_CLAIMABLE_SUCCESS';
export const ACTION_GET_HISTORY = 'ACTION_GET_HISTORY';
export const ACTION_GET_HISTORY_ERROR = 'ACTION_GET_HISTORY_ERROR';
export const ACTION_GET_HISTORY_SUCCESS = 'ACTION_GET_HISTORY_SUCCESS';
export const ACTION_GET_PENDING = 'ACTION_GET_PENDING';
export const ACTION_GET_PENDING_ERROR = 'ACTION_GET_PENDING_ERROR';
export const ACTION_GET_PENDING_SUCCESS = 'ACTION_GET_PENDING_SUCCESS';
export const ACTION_PUBLISH = 'ACTION_PUBLISH';
export const ACTION_PUBLISHED = 'ACTION_PUBLISHED';
export const ACTION_SAVE_ERROR = 'ACTION_SAVE_ERROR';
export const ACTION_UPDATE = 'ACTION_UPDATE';

export const APP_READY = 'APP_READY';

export const APP_SETTINGS_TOGGLE = 'APP_SETTINGS_TOGGLE';
export const APP_SETTINGS_UPDATE = 'APP_SETTINGS_UPDATE';

export const AUTH_DIALOG_TOGGLE = 'AUTH_DIALOG_TOGGLE';

export const BACKUP_KEYS_ERROR = 'BACKUP_KEYS_ERROR';
export const BACKUP_KEYS_REQUEST = 'BACKUP_KEYS_REQUEST';
export const BACKUP_KEYS_SUCCESS = 'BACKUP_KEYS_SUCCESS';

export const BOOTSTRAP_HOME = 'BOOTSTRAP_HOME';
export const BOOTSTRAP_HOME_SUCCESS = 'BOOTSTRAP_HOME_SUCCESS';

export const CLEAR_SYNC_STATUS = 'CLEAR_SYNC_STATUS';
export const CLEAN_STORE = 'CLEAN_STORE';

export const COMMENTS_CHECK_NEW = 'COMMENTS_CHECK_NEW';
export const COMMENTS_CHECK_NEW_ERROR = 'COMMENTS_CHECK_NEW_ERROR';
export const COMMENTS_CHECK_NEW_SUCCESS = 'COMMENTS_CHECK_NEW_SUCCESS';
export const COMMENTS_CLEAN = 'COMMENTS_CLEAN';
export const COMMENTS_DOWNVOTE = 'COMMENTS_DOWNVOTE';
export const COMMENTS_DOWNVOTE_ERROR = 'COMMENTS_DOWNVOTE_ERROR';
export const COMMENTS_DOWNVOTE_SUCCESS = 'COMMENTS_DOWNVOTE_SUCCESS';
export const COMMENTS_GET_COUNT = 'COMMENTS_GET_COUNT';
export const COMMENTS_GET_COUNT_ERROR = 'COMMENTS_GET_COUNT_ERROR';
export const COMMENTS_GET_COUNT_SUCCESS = 'COMMENTS_GET_COUNT_SUCCESS';
export const COMMENTS_GET_SCORE = 'COMMENTS_GET_SCORE';
export const COMMENTS_GET_SCORE_ERROR = 'COMMENTS_GET_SCORE_ERROR';
export const COMMENTS_GET_SCORE_SUCCESS = 'COMMENTS_GET_SCORE_SUCCESS';
export const COMMENTS_GET_VOTE_OF = 'COMMENTS_GET_VOTE_OF';
export const COMMENTS_GET_VOTE_OF_ERROR = 'COMMENTS_GET_VOTE_OF_ERROR';
export const COMMENTS_GET_VOTE_OF_SUCCESS = 'COMMENTS_GET_VOTE_OF_SUCCESS';
export const COMMENTS_ITERATOR = 'COMMENTS_ITERATOR';
export const COMMENTS_ITERATOR_ERROR = 'COMMENTS_ITERATOR_ERROR';
export const COMMENTS_ITERATOR_SUCCESS = 'COMMENTS_ITERATOR_SUCCESS';
export const COMMENTS_ITERATOR_REVERSED_SUCCESS = 'COMMENTS_ITERATOR_REVERSED_SUCCESS';
export const COMMENTS_LOAD_NEW = 'COMMENTS_LOAD_NEW';
export const COMMENTS_MORE_ITERATOR = 'COMMENTS_MORE_ITERATOR';
export const COMMENTS_MORE_ITERATOR_ERROR = 'COMMENTS_MORE_ITERATOR_ERROR';
export const COMMENTS_MORE_ITERATOR_SUCCESS = 'COMMENTS_MORE_ITERATOR_SUCCESS';
export const COMMENTS_PUBLISH = 'COMMENTS_PUBLISH';
export const COMMENTS_PUBLISH_ERROR = 'COMMENTS_PUBLISH_ERROR';
export const COMMENTS_PUBLISH_SUCCESS = 'COMMENTS_PUBLISH_SUCCESS';
export const COMMENTS_RESOLVE_IPFS_HASH = 'COMMENTS_RESOLVE_IPFS_HASH';
export const COMMENTS_RESOLVE_IPFS_HASH_ERROR = 'COMMENTS_RESOLVE_IPFS_HASH_ERROR';
export const COMMENTS_RESOLVE_IPFS_HASH_SUCCESS = 'COMMENTS_RESOLVE_IPFS_HASH_SUCCESS';
export const COMMENTS_UPVOTE = 'COMMENTS_UPVOTE';
export const COMMENTS_UPVOTE_ERROR = 'COMMENTS_UPVOTE_ERROR';
export const COMMENTS_UPVOTE_SUCCESS = 'COMMENTS_UPVOTE_SUCCESS';

export const DASHBOARD_ADD = 'DASHBOARD_ADD';
export const DASHBOARD_ADD_ERROR = 'DASHBOARD_ADD_ERROR';
export const DASHBOARD_ADD_SUCCESS = 'DASHBOARD_ADD_SUCCESS';
export const DASHBOARD_ADD_COLUMN = 'DASHBOARD_ADD_COLUMN';
export const DASHBOARD_ADD_COLUMN_ERROR = 'DASHBOARD_ADD_COLUMN_ERROR';
export const DASHBOARD_ADD_COLUMN_SUCCESS = 'DASHBOARD_ADD_COLUMN_SUCCESS';
export const DASHBOARD_ADD_FIRST = 'DASHBOARD_ADD_FIRST';
export const DASHBOARD_ADD_FIRST_SUCCESS = 'DASHBOARD_ADD_FIRST_SUCCESS';
export const DASHBOARD_ADD_NEW_COLUMN = 'DASHBOARD_ADD_NEW_COLUMN';
export const DASHBOARD_DELETE = 'DASHBOARD_DELETE';
export const DASHBOARD_DELETE_ERROR = 'DASHBOARD_DELETE_ERROR';
export const DASHBOARD_DELETE_SUCCESS = 'DASHBOARD_DELETE_SUCCESS';
export const DASHBOARD_DELETE_COLUMN = 'DASHBOARD_DELETE_COLUMN';
export const DASHBOARD_DELETE_COLUMN_ERROR = 'DASHBOARD_DELETE_COLUMN_ERROR';
export const DASHBOARD_DELETE_COLUMN_SUCCESS = 'DASHBOARD_DELETE_COLUMN_SUCCESS';
export const DASHBOARD_DELETE_NEW_COLUMN = 'DASHBOARD_DELETE_NEW_COLUMN';
export const DASHBOARD_GET_ACTIVE_ERROR = 'DASHBOARD_GET_ACTIVE_ERROR';
export const DASHBOARD_GET_ACTIVE_SUCCESS = 'DASHBOARD_GET_ACTIVE_SUCCESS';
export const DASHBOARD_GET_ALL_ERROR = 'DASHBOARD_GET_ALL_ERROR';
export const DASHBOARD_GET_ALL_SUCCESS = 'DASHBOARD_GET_ALL_SUCCESS';
export const DASHBOARD_RENAME = 'DASHBOARD_RENAME';
export const DASHBOARD_RENAME_ERROR = 'DASHBOARD_RENAME_ERROR';
export const DASHBOARD_RENAME_SUCCESS = 'DASHBOARD_RENAME_SUCCESS';
export const DASHBOARD_RESET_NEW_COLUMN = 'DASHBOARD_RESET_NEW_COLUMN';
export const DASHBOARD_SEARCH = 'DASHBOARD_SEARCH';
export const DASHBOARD_SET_ACTIVE = 'DASHBOARD_SET_ACTIVE';
export const DASHBOARD_SET_ACTIVE_ERROR = 'DASHBOARD_SET_ACTIVE_ERROR';
export const DASHBOARD_SET_ACTIVE_SUCCESS = 'DASHBOARD_SET_ACTIVE_SUCCESS';
export const DASHBOARD_TOGGLE_TAG_COLUMN = 'DASHBOARD_TOGGLE_TAG_COLUMN';
export const DASHBOARD_TOGGLE_TAG_COLUMN_ERROR = 'DASHBOARD_TOGGLE_TAG_COLUMN_ERROR';
export const DASHBOARD_TOGGLE_TAG_COLUMN_SUCCESS = 'DASHBOARD_TOGGLE_TAG_COLUMN_SUCCESS';
export const DASHBOARD_UPDATE_COLUMN = 'DASHBOARD_UPDATE_COLUMN';
export const DASHBOARD_UPDATE_COLUMN_ERROR = 'DASHBOARD_UPDATE_COLUMN_ERROR';
export const DASHBOARD_UPDATE_COLUMN_SUCCESS = 'DASHBOARD_UPDATE_COLUMN_SUCCESS';
export const DASHBOARD_UPDATE_NEW_COLUMN = 'DASHBOARD_UPDATE_NEW_COLUMN';

export const DRAFT_AUTOSAVE = 'DRAFT_AUTOSAVE';
export const DRAFT_AUTOSAVE_SUCCESS = 'DRAFT_AUTOSAVE_SUCCESS';
export const DRAFT_AUTOSAVE_ERROR = 'DRAFT_AUTOSAVE_ERROR';
export const DRAFT_CREATE = 'DRAFT_CREATE';
export const DRAFT_CREATE_SUCCESS = 'DRAFT_CREATE_SUCCESS';
export const DRAFT_CREATE_ERROR = 'DRAFT_CREATE_ERROR';
export const DRAFT_DELETE = 'DRAFT_DELETE';
export const DRAFT_DELETE_SUCCESS = 'DRAFT_DELETE_SUCCESS';
export const DRAFT_DELETE_ERROR = 'DRAFT_DELETE_ERROR';
export const DRAFT_GET_SUCCESS = 'DRAFT_GET_SUCCESS';
export const DRAFT_GET_ERROR = 'DRAFT_GET_ERROR';
export const DRAFT_GET_BY_ID = 'DRAFT_GET_BY_ID';
export const DRAFT_GET_BY_ID_SUCCESS = 'DRAFT_GET_BY_ID_SUCCESS';
export const DRAFT_GET_BY_ID_ERROR = 'DRAFT_GET_BY_ID_ERROR';
export const DRAFTS_GET = 'DRAFTS_GET';
export const DRAFTS_GET_SUCCESS = 'DRAFTS_GET_SUCCESS';
export const DRAFTS_GET_ERROR = 'DRAFTS_GET_ERROR';
export const DRAFTS_GET_COUNT = 'DRAFTS_GET_COUNT';
export const DRAFTS_GET_COUNT_SUCCESS = 'DRAFTS_GET_COUNT_SUCCESS';
export const DRAFTS_GET_COUNT_ERROR = 'DRAFTS_GET_COUNT_ERROR';
export const DRAFTS_GET_PUBLISHING = 'DRAFTS_GET_PUBLISHING';
export const DRAFTS_GET_PUBLISHING_SUCCESS = 'DRAFTS_GET_PUBLISHING_SUCCESS';
export const DRAFTS_GET_PUBLISHING_ERROR = 'DRAFTS_GET_PUBLISHING_ERROR';
export const DRAFT_IMAGE_SAVE = 'DRAFTS_IMAGE_SAVE';
export const DRAFT_IMAGE_SAVE_SUCCESS = 'DRAFT_IMAGE_SAVE_SUCCESS';
export const DRAFT_IMAGE_SAVE_ERROR = 'DRAFT_IMAGE_SAVE_ERROR';
export const DRAFT_PAUSE_PUBLISHING = 'DRAFT_PAUSE_PUBLISHING';
export const DRAFT_PUBLISH = 'DRAFT_PUBLISH';
export const DRAFT_PUBLISH_SUCCESS = 'DRAFT_PUBLISH_SUCCESS';
export const DRAFT_PUBLISH_ERROR = 'DRAFT_PUBLISH_ERROR';
export const DRAFT_PUBLISH_UPDATE = 'DRAFT_PUBLISH_UPDATE';
export const DRAFT_PUBLISH_UPDATE_ERROR = 'DRAFT_PUBLISH_UPDATE_ERROR';
export const DRAFT_PUBLISH_UPDATE_SUCCESS = 'DRAFT_PUBLISH_UPDATE_SUCCESS';
export const DRAFT_REVERT_TO_VERSION = 'DRAFT_REVERT_TO_VERSION';
export const DRAFT_REVERT_TO_VERSION_ERROR = 'DRAFT_REVERT_TO_VERSION_ERROR';
export const DRAFT_REVERT_TO_VERSION_SUCCESS = 'DRAFT_REVERT_TO_VERSION_SUCCESS';
export const DRAFT_SAVE = 'DRAFT_SAVE';
export const DRAFT_SAVE_SUCCESS = 'DRAFT_SAVE_SUCCESS';
export const DRAFT_SAVE_ERROR = 'DRAFT_SAVE_ERROR';
export const DRAFT_START_PUBLISHING = 'DRAFT_START_PUBLISHING';
export const DRAFT_UPDATE = 'DRAFT_UPDATE';
export const DRAFT_UPDATE_SUCCESS = 'DRAFT_UPDATE_SUCCESS';
export const DRAFT_UPDATE_ERROR = 'DRAFT_UPDATE_ERROR';

export const ENTRY_ADD_CLAIM_ACTION = 'ADD_CLAIM_ACTION';
export const ENTRY_ADD_DOWNVOTE_ACTION = 'ADD_DOWNVOTE_ACTION';
export const ENTRY_ADD_UPVOTE_ACTION = 'ADD_UPVOTE_ACTION';
export const DELETE_PENDING_ACTION = 'DELETE_PENDING_ACTION';

export const ENTRIES_GET_AS_DRAFTS_SUCCESS = 'ENTRIES_GET_AS_DRAFTS_SUCCESS';
export const ENTRIES_GET_AS_DRAFTS_ERROR = 'ENTRIES_GET_AS_DRAFTS_ERROR';

export const ENTRY_CAN_CLAIM = 'ENTRY_CAN_CLAIM';
export const ENTRY_CAN_CLAIM_ERROR = 'ENTRY_CAN_CLAIM_ERROR';
export const ENTRY_CAN_CLAIM_SUCCESS = 'ENTRY_CAN_CLAIM_SUCCESS';
export const ENTRY_CAN_CLAIM_VOTE = 'ENTRY_CAN_CLAIM_VOTE';
export const ENTRY_CAN_CLAIM_VOTE_ERROR = 'ENTRY_CAN_CLAIM_VOTE_ERROR';
export const ENTRY_CAN_CLAIM_VOTE_SUCCESS = 'ENTRY_CAN_CLAIM_VOTE_SUCCESS';
export const ENTRY_CLAIM = 'ENTRY_CLAIM';
export const ENTRY_CLAIM_ERROR = 'ENTRY_CLAIM_ERROR';
export const ENTRY_CLAIM_SUCCESS = 'ENTRY_CLAIM_SUCCESS';
export const ENTRY_CLAIM_VOTE = 'ENTRY_CLAIM_VOTE';
export const ENTRY_CLAIM_VOTE_ERROR = 'ENTRY_CLAIM_VOTE_ERROR';
export const ENTRY_CLAIM_VOTE_SUCCESS = 'ENTRY_CLAIM_VOTE_SUCCESS';
export const ENTRY_CLEAN_FULL = 'ENTRY_CLEAN_FULL';

export const ENTRY_DOWNVOTE = 'ENTRY_DOWNVOTE';
export const ENTRY_DOWNVOTE_ERROR = 'ENTRY_DOWNVOTE_ERROR';
export const ENTRY_DOWNVOTE_SUCCESS = 'ENTRY_DOWNVOTE_SUCCESS';

export const ENTRY_GET_BALANCE = 'ENTRY_GET_BALANCE';
export const ENTRY_GET_BALANCE_ERROR = 'ENTRY_GET_BALANCE_ERROR';
export const ENTRY_GET_BALANCE_SUCCESS = 'ENTRY_GET_BALANCE_SUCCESS';
export const ENTRY_GET_FULL = 'ENTRY_GET_FULL';
export const ENTRY_GET_FULL_ERROR = 'ENTRY_GET_FULL_ERROR';
export const ENTRY_GET_FULL_SUCCESS = 'ENTRY_GET_FULL_SUCCESS';
export const ENTRY_GET_FULL_AS_DRAFT = 'ENTRY_GET_FULL_AS_DRAFT';
export const ENTRY_GET_FULL_AS_DRAFT_ERROR = 'ENTRY_GET_FULL_AS_DRAFT_ERROR';
export const ENTRY_GET_FULL_AS_DRAFT_SUCCESS = 'ENTRY_GET_FULL_AS_DRAFT_SUCCESS';
export const ENTRY_GET_VERSION_PUBLISHED_DATE_SUCCESS = 'ENTRY_GET_VERSION_PUBLISHED_DATE_SUCCESS';
export const ENTRY_GET_VERSION_PUBLISHED_DATE_ERROR = 'ENTRY_GET_VERSION_PUBLISHED_DATE_ERROR';
export const ENTRY_GET_LATEST_VERSION = 'ENTRY_GET_LATEST_VERSION';
export const ENTRY_GET_LATEST_VERSION_ERROR = 'ENTRY_GET_LATEST_VERSION_ERROR';
export const ENTRY_GET_LATEST_VERSION_SUCCESS = 'ENTRY_GET_LATEST_VERSION_SUCCESS';
export const ENTRY_GET_SCORE = 'ENTRY_GET_SCORE';
export const ENTRY_GET_SCORE_ERROR = 'ENTRY_GET_SCORE_ERROR';
export const ENTRY_GET_SCORE_SUCCESS = 'ENTRY_GET_SCORE_SUCCESS';
export const ENTRY_GET_SHORT = 'ENTRY_GET_SHORT';
export const ENTRY_GET_SHORT_ERROR = 'ENTRY_GET_SHORT_ERROR';
export const ENTRY_GET_SHORT_SUCCESS = 'ENTRY_GET_SHORT_SUCCESS';
export const ENTRY_GET_VOTE_OF = 'ENTRY_GET_VOTE_OF';
export const ENTRY_GET_VOTE_OF_ERROR = 'ENTRY_GET_VOTE_OF_ERROR';
export const ENTRY_GET_VOTE_OF_SUCCESS = 'ENTRY_GET_VOTE_OF_SUCCESS';

export const ENTRY_GET_VOTE_RATIO = 'ENTRY_GET_VOTE_RATIO';
export const ENTRY_GET_VOTE_RATIO_SUCCESS = 'ENTRY_GET_VOTE_RATIO_SUCCESS';
export const ENTRY_GET_VOTE_RATIO_ERROR = 'ENTRY_GET_VOTE_RATIO_ERROR';

export const ENTRY_LIST_ITERATOR = 'ENTRY_LIST_ITERATOR';
export const ENTRY_LIST_ITERATOR_SUCCESS = 'ENTRY_LIST_ITERATOR_SUCCESS';

export const ENTRY_MORE_LIST_ITERATOR = 'ENTRY_MORE_LIST_ITERATOR';
export const ENTRY_MORE_LIST_ITERATOR_SUCCESS = 'ENTRY_MORE_LIST_ITERATOR_SUCCESS';
export const ENTRY_MORE_NEWEST_ITERATOR = 'ENTRY_MORE_NEWEST_ITERATOR';
export const ENTRY_MORE_NEWEST_ITERATOR_ERROR = 'ENTRY_MORE_NEWEST_ITERATOR_ERROR';
export const ENTRY_MORE_NEWEST_ITERATOR_SUCCESS = 'ENTRY_MORE_NEWEST_ITERATOR_SUCCESS';
export const ENTRY_MORE_PROFILE_ITERATOR = 'ENTRY_MORE_PROFILE_ITERATOR';
export const ENTRY_MORE_PROFILE_ITERATOR_ERROR = 'ENTRY_MORE_PROFILE_ITERATOR_ERROR';
export const ENTRY_MORE_PROFILE_ITERATOR_SUCCESS = 'ENTRY_MORE_PROFILE_ITERATOR_SUCCESS';
export const ENTRY_MORE_STREAM_ITERATOR = 'ENTRY_MORE_STREAM_ITERATOR';
export const ENTRY_MORE_STREAM_ITERATOR_ERROR = 'ENTRY_MORE_STREAM_ITERATOR_ERROR';
export const ENTRY_MORE_STREAM_ITERATOR_SUCCESS = 'ENTRY_MORE_STREAM_ITERATOR_SUCCESS';
export const ENTRY_MORE_TAG_ITERATOR = 'ENTRY_MORE_TAG_ITERATOR';
export const ENTRY_MORE_TAG_ITERATOR_ERROR = 'ENTRY_MORE_TAG_ITERATOR_ERROR';
export const ENTRY_MORE_TAG_ITERATOR_SUCCESS = 'ENTRY_MORE_TAG_ITERATOR_SUCCESS';

export const ENTRY_NEWEST_ITERATOR = 'ENTRY_NEWEST_ITERATOR';
export const ENTRY_NEWEST_ITERATOR_ERROR = 'ENTRY_NEWEST_ITERATOR_ERROR';
export const ENTRY_NEWEST_ITERATOR_SUCCESS = 'ENTRY_NEWEST_ITERATOR_SUCCESS';

export const ENTRY_PAGE_HIDE = 'ENTRY_PAGE_HIDE';
export const ENTRY_PAGE_SHOW = 'ENTRY_PAGE_SHOW';

export const ENTRY_PROFILE_ITERATOR = 'ENTRY_PROFILE_ITERATOR';
export const ENTRY_PROFILE_ITERATOR_ERROR = 'ENTRY_PROFILE_ITERATOR_ERROR';
export const ENTRY_PROFILE_ITERATOR_SUCCESS = 'ENTRY_PROFILE_ITERATOR_SUCCESS';

export const ENTRY_RESOLVE_IPFS_HASH = 'ENTRY_RESOLVE_IPFS_HASH';
export const ENTRY_RESOLVE_IPFS_HASH_ERROR = 'ENTRY_RESOLVE_IPFS_HASH_ERROR';
export const ENTRY_RESOLVE_IPFS_HASH_SUCCESS = 'ENTRY_RESOLVE_IPFS_HASH_SUCCESS';

export const ENTRY_STREAM_ITERATOR = 'ENTRY_STREAM_ITERATOR';
export const ENTRY_STREAM_ITERATOR_ERROR = 'ENTRY_STREAM_ITERATOR_ERROR';
export const ENTRY_STREAM_ITERATOR_SUCCESS = 'ENTRY_STREAM_ITERATOR_SUCCESS';

export const ENTRY_RESOLVE_IPFS_HASH_AS_DRAFTS_SUCCESS = 'ENTRY_RESOLVE_IPFS_HASH_AS_DRAFTS_SUCCESS';
export const ENTRY_RESOLVE_IPFS_HASH_AS_DRAFTS_ERROR = 'ENTRY_RESOLVE_IPFS_HASH_AS_DRAFTS_ERROR';

export const ENTRY_UPVOTE = 'ENTRY_UPVOTE';
export const ENTRY_UPVOTE_ERROR = 'ENTRY_UPVOTE_ERROR';
export const ENTRY_UPVOTE_SUCCESS = 'ENTRY_UPVOTE_SUCCESS';

export const ENTRY_TAG_ITERATOR = 'ENTRY_TAG_ITERATOR';
export const ENTRY_TAG_ITERATOR_ERROR = 'ENTRY_TAG_ITERATOR_ERROR';
export const ENTRY_TAG_ITERATOR_SUCCESS = 'ENTRY_TAG_ITERATOR_SUCCESS';

export const ENTRY_VOTE_COST = 'ENTRY_VOTE_COST';
export const ENTRY_VOTE_COST_ERROR = 'ENTRY_VOTE_COST_ERROR';
export const ENTRY_VOTE_COST_SUCCESS = 'ENTRY_VOTE_COST_SUCCESS';

export const ERROR_DELETE_FATAL = 'ERROR_DELETE_FATAL';
export const ERROR_DELETE_NON_FATAL = 'ERROR_DELETE_NON_FATAL';
export const ERROR_DISPLAY = 'ERROR_DISPLAY';

export const GENERAL_SETTINGS = 'GENERAL_SETTINGS';
export const GENERAL_SETTINGS_ERROR = 'GENERAL_SETTINGS_ERROR';
export const GENERAL_SETTINGS_SUCCESS = 'GENERAL_SETTINGS_SUCCESS';
export const GENERAL_SETTINGS_SAVE = 'GENERAL_SETTINGS_SAVE';
export const GENERAL_SETTINGS_SAVE_ERROR = 'GENERAL_SETTINGS_SAVE_ERROR';
export const GENERAL_SETTINGS_SAVE_SUCCESS = 'GENERAL_SETTINGS_SAVE_SUCCESS';

export const GETH_GET_LOGS = 'GETH_GET_LOGS';
export const GETH_GET_LOGS_SUCCESS = 'GETH_GET_LOGS_SUCCESS';
export const GETH_GET_OPTIONS_ERROR = 'GETH_GET_OPTIONS_ERROR';
export const GETH_GET_OPTIONS_SUCCESS = 'GETH_GET_OPTIONS_SUCCESS';
export const GETH_GET_STATUS = 'GETH_GET_STATUS';
export const GETH_GET_STATUS_ERROR = 'GETH_GET_STATUS_ERROR';
export const GETH_GET_STATUS_SUCCESS = 'GETH_GET_STATUS_SUCCESS';
export const GETH_GET_SYNC_STATUS = 'GETH_GET_SYNC_STATUS';
export const GETH_GET_SYNC_STATUS_ERROR = 'GETH_GET_SYNC_STATUS_ERROR';
export const GETH_GET_SYNC_STATUS_SUCCESS = 'GETH_GET_SYNC_STATUS_SUCCESS';
export const GETH_PAUSE_SYNC = 'GETH_PAUSE_SYNC';
export const GETH_RESET_BUSY = 'GETH_RESET_BUSY';
export const GETH_RESUME_SYNC = 'GETH_RESUME_SYNC';
export const GETH_SAVE_SETTINGS = 'GETH_SAVE_SETTINGS';
export const GETH_SAVE_SETTINGS_ERROR = 'GETH_SAVE_SETTINGS_ERROR';
export const GETH_SAVE_SETTINGS_SUCCESS = 'GETH_SAVE_SETTINGS_SUCCESS';
export const GETH_SETTINGS = 'GETH_SETTINGS';
export const GETH_SETTINGS_ERROR = 'GETH_SETTINGS_ERROR';
export const GETH_SETTINGS_SUCCESS = 'GETH_SETTINGS_SUCCESS';
export const GETH_START = 'GETH_START';
export const GETH_START_ERROR = 'GETH_START_ERROR';
export const GETH_START_LOGGER = 'GETH_START_LOGGER';
export const GETH_START_SUCCESS = 'GETH_START_SUCCESS';
export const GETH_STOP = 'GETH_STOP';
export const GETH_STOP_ERROR = 'GETH_STOP_ERROR';
export const GETH_STOP_LOGGER = 'GETH_STOP_LOGGER';
export const GETH_STOP_SUCCESS = 'GETH_STOP_SUCCESS';
export const GETH_STOP_SYNC = 'GETH_STOP_SYNC';

export const HIDE_REPORT_MODAL = 'HIDE_REPORT_MODAL';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const HIDE_TERMS = 'HIDE_TERMS';

export const HIGHLIGHT_DELETE = 'HIGHLIGHT_DELETE';
export const HIGHLIGHT_DELETE_ERROR = 'HIGHLIGHT_DELETE_ERROR';
export const HIGHLIGHT_DELETE_SUCCESS = 'HIGHLIGHT_DELETE_SUCCESS';
export const HIGHLIGHT_EDIT_NOTES = 'HIGHLIGHT_EDIT_NOTES';
export const HIGHLIGHT_EDIT_NOTES_ERROR = 'HIGHLIGHT_EDIT_NOTES_ERROR';
export const HIGHLIGHT_EDIT_NOTES_SUCCESS = 'HIGHLIGHT_EDIT_NOTES_SUCCESS';
export const HIGHLIGHT_GET_ALL_ERROR = 'HIGHLIGHT_GET_ALL_ERROR';
export const HIGHLIGHT_GET_ALL_SUCCESS = 'HIGHLIGHT_GET_ALL_SUCCESS';
export const HIGHLIGHT_SAVE = 'HIGHLIGHT_SAVE';
export const HIGHLIGHT_SAVE_ERROR = 'HIGHLIGHT_SAVE_ERROR';
export const HIGHLIGHT_SAVE_SUCCESS = 'HIGHLIGHT_SAVE_SUCCESS';
export const HIGHLIGHT_SEARCH = 'HIGHLIGHT_SEARCH';
export const HIGHLIGHT_SEARCH_ERROR = 'HIGHLIGHT_SEARCH_ERROR';
export const HIGHLIGHT_SEARCH_SUCCESS = 'HIGHLIGHT_SEARCH_SUCCESS';
export const HIGHLIGHT_TOGGLE_NOTE_EDITABLE = 'HIGHLIGHT_TOGGLE_NOTE_EDITABLE';
export const HIGHLIGHT_TOGGLE_EDITING = 'HIGHLIGHT_TOGGLE_EDITING';

export const IPFS_GET_CONFIG_ERROR = 'IPFS_GET_CONFIG_ERROR';
export const IPFS_GET_CONFIG_SUCCESS = 'IPFS_GET_CONFIG_SUCCESS';
export const IPFS_GET_LOGS = 'IPFS_GET_LOGS';
export const IPFS_GET_LOGS_SUCCESS = 'IPFS_GET_LOGS_SUCCESS';
export const IPFS_GET_PORTS = 'IPFS_GET_PORTS';
export const IPFS_GET_PORTS_ERROR = 'IPFS_GET_PORTS_ERROR';
export const IPFS_GET_PORTS_SUCCESS = 'IPFS_GET_PORTS_SUCCESS';
export const IPFS_GET_STATUS = 'IPFS_GET_STATUS';
export const IPFS_GET_STATUS_ERROR = 'IPFS_GET_STATUS_ERROR';
export const IPFS_GET_STATUS_SUCCESS = 'IPFS_GET_STATUS_SUCCESS';
export const IPFS_RESET_BUSY = 'IPFS_RESET_BUSY';
export const IPFS_RESET_PORTS = 'IPFS_RESET_PORTS';
export const IPFS_SAVE_SETTINGS = 'IPFS_SAVE_SETTINGS';
export const IPFS_SAVE_SETTINGS_ERROR = 'IPFS_SAVE_SETTINGS_ERROR';
export const IPFS_SAVE_SETTINGS_SUCCESS = 'IPFS_SAVE_SETTINGS_SUCCESS';
export const IPFS_SET_PORTS = 'IPFS_SET_PORTS';
export const IPFS_SET_PORTS_ERROR = 'IPFS_SET_PORTS_ERROR';
export const IPFS_SET_PORTS_SUCCESS = 'IPFS_SET_PORTS_SUCCESS';
export const IPFS_SETTINGS = 'IPFS_SETTINGS';
export const IPFS_SETTINGS_ERROR = 'IPFS_SETTINGS_ERROR';
export const IPFS_SETTINGS_SUCCESS = 'IPFS_SETTINGS_SUCCESS';
export const IPFS_START = 'IPFS_START';
export const IPFS_START_ERROR = 'IPFS_START_ERROR';
export const IPFS_START_LOGGER = 'IPFS_START_LOGGER';
export const IPFS_START_SUCCESS = 'IPFS_START_SUCCESS';
export const IPFS_STOP = 'IPFS_STOP';
export const IPFS_STOP_ERROR = 'IPFS_STOP_ERROR';
export const IPFS_STOP_LOGGER = 'IPFS_STOP_LOGGER';
export const IPFS_STOP_SUCCESS = 'IPFS_STOP_SUCCESS';

export const NOTIFICATION_DISPLAY = 'NOTIFICATION_DISPLAY';

export const LICENSE_GET_ALL = 'LICENSE_GET_ALL';
export const LICENSE_GET_ALL_ERROR = 'LICENSE_GET_ALL_ERROR';
export const LICENSE_GET_ALL_SUCCESS = 'LICENSE_GET_ALL_SUCCESS';

export const LIST_ADD = 'LIST_ADD';
export const LIST_ADD_ERROR = 'LIST_ADD_ERROR';
export const LIST_ADD_SUCCESS = 'LIST_ADD_SUCCESS';
export const LIST_DELETE = 'LIST_DELETE';
export const LIST_DELETE_ENTRY = 'LIST_DELETE_ENTRY';
export const LIST_DELETE_ENTRY_ERROR = 'LIST_DELETE_ENTRY_ERROR';
export const LIST_DELETE_ENTRY_SUCCESS = 'LIST_DELETE_ENTRY_SUCCESS';
export const LIST_DELETE_ERROR = 'LIST_DELETE_ERROR';
export const LIST_DELETE_SUCCESS = 'LIST_DELETE_SUCCESS';
export const LIST_EDIT = 'LIST_EDIT';
export const LIST_EDIT_ERROR = 'LIST_EDIT_ERROR';
export const LIST_EDIT_SUCCESS = 'LIST_EDIT_SUCCESS';
export const LIST_GET_ALL_ERROR = 'LIST_GET_ALL_ERROR';
export const LIST_GET_ALL_SUCCESS = 'LIST_GET_ALL_SUCCESS';
export const LIST_GET_FULL = 'LIST_GET_FULL';
export const LIST_GET_FULL_ERROR = 'LIST_GET_FULL_ERROR';
export const LIST_GET_FULL_SUCCESS = 'LIST_GET_FULL_SUCCESS';
export const LIST_SEARCH = 'LIST_SEARCH';
export const LIST_SEARCH_ERROR = 'LIST_SEARCH_ERROR';
export const LIST_SEARCH_SUCCESS = 'LIST_SEARCH_SUCCESS';
export const LIST_TOGGLE_ENTRY = 'LIST_TOGGLE_ENTRY';
export const LIST_TOGGLE_ENTRY_ERROR = 'LIST_TOGGLE_ENTRY_ERROR';
export const LIST_TOGGLE_ENTRY_SUCCESS = 'LIST_TOGGLE_ENTRY_SUCCESS';

export const LISTEN_FAUCET_TX = 'LISTEN_FAUCET_TX';
export const LISTEN_PUBLISH_TX = 'LISTEN_PUBLISH_TX';

export const PANEL_HIDE = 'PANEL_HIDE';
export const PANEL_SHOW = 'PANEL_SHOW';

export const PENDING_ACTION_DELETE = 'PENDING_ACTION_DELETE';
export const PENDING_ACTION_UPDATE = 'PENDING_ACTION_UPDATE';
export const PENDING_ACTION_SAVE = 'PENDING_ACTION_SAVE';
export const PENDING_ACTION_SAVE_SUCCESS = 'PENDING_ACTION_SAVE_SUCCESS';

export const PROFILE_AETH_TRANSFERS_ITERATOR = 'PROFILE_AETH_TRANSFERS_ITERATOR';
export const PROFILE_AETH_TRANSFERS_ITERATOR_ERROR = 'PROFILE_AETH_TRANSFERS_ITERATOR_ERROR';
export const PROFILE_AETH_TRANSFERS_ITERATOR_SUCCESS = 'PROFILE_AETH_TRANSFERS_ITERATOR_SUCCESS';

export const PROFILE_BOND_AETH = 'PROFILE_BOND_AETH';
export const PROFILE_BOND_AETH_ERROR = 'PROFILE_BOND_AETH_ERROR';
export const PROFILE_BOND_AETH_SUCCESS = 'PROFILE_BOND_AETH_SUCCESS';

export const PROFILE_CLEAR_LOCAL = 'PROFILE_CLEAR_LOCAL';
export const PROFILE_CLEAR_LOGIN_ERRORS = 'PROFILE_CLEAR_LOGIN_ERRORS';

export const PROFILE_CREATE_ETH_ADDRESS = 'PROFILE_CREATE_ETH_ADDRESS';
export const PROFILE_CREATE_ETH_ADDRESS_ERROR = 'PROFILE_CREATE_ETH_ADDRESS_ERROR';
export const PROFILE_CREATE_ETH_ADDRESS_SUCCESS = 'PROFILE_CREATE_ETH_ADDRESS_SUCCESS';

export const PROFILE_CYCLE_AETH = 'PROFILE_CYCLE_AETH';
export const PROFILE_CYCLE_AETH_ERROR = 'PROFILE_CYCLE_AETH_ERROR';
export const PROFILE_CYCLE_AETH_SUCCESS = 'PROFILE_CYCLE_AETH_SUCCESS';

export const PROFILE_CYCLING_STATES = 'PROFILE_CYCLING_STATES';
export const PROFILE_CYCLING_STATES_ERROR = 'PROFILE_CYCLING_STATES_ERROR';
export const PROFILE_CYCLING_STATES_SUCCESS = 'PROFILE_CYCLING_STATES_SUCCESS';

export const PROFILE_DELETE_LOGGED = 'PROFILE_DELETE_LOGGED';
export const PROFILE_DELETE_LOGGED_ERROR = 'PROFILE_DELETE_LOGGED_ERROR';
export const PROFILE_DELETE_LOGGED_SUCCESS = 'PROFILE_DELETE_LOGGED_SUCCESS';

export const PROFILE_EDIT_TOGGLE = 'PROFILE_EDIT_TOGGLE';

export const PROFILE_ESSENCE_ITERATOR = 'PROFILE_ESSENCE_ITERATOR';
export const PROFILE_ESSENCE_ITERATOR_ERROR = 'PROFILE_ESSENCE_ITERATOR_ERROR';
export const PROFILE_ESSENCE_ITERATOR_SUCCESS = 'PROFILE_ESSENCE_ITERATOR_SUCCESS';

export const PROFILE_EXISTS = 'PROFILE_EXISTS';
export const PROFILE_EXISTS_ERROR = 'PROFILE_EXISTS_ERROR';
export const PROFILE_EXISTS_SUCCESS = 'PROFILE_EXISTS_SUCCESS';

export const PROFILE_FOLLOW = 'PROFILE_FOLLOW';
export const PROFILE_FOLLOW_ERROR = 'PROFILE_FOLLOW_ERROR';
export const PROFILE_FOLLOW_SUCCESS = 'PROFILE_FOLLOW_SUCCESS';
export const PROFILE_FOLLOWERS_ITERATOR = 'PROFILE_FOLLOWERS_ITERATOR';
export const PROFILE_FOLLOWERS_ITERATOR_ERROR = 'PROFILE_FOLLOWERS_ITERATOR_ERROR';
export const PROFILE_FOLLOWERS_ITERATOR_SUCCESS = 'PROFILE_FOLLOWERS_ITERATOR_SUCCESS';
export const PROFILE_FOLLOWINGS_ITERATOR = 'PROFILE_FOLLOWINGS_ITERATOR';
export const PROFILE_FOLLOWINGS_ITERATOR_ERROR = 'PROFILE_FOLLOWINGS_ITERATOR_ERROR';
export const PROFILE_FOLLOWINGS_ITERATOR_SUCCESS = 'PROFILE_FOLLOWINGS_ITERATOR_SUCCESS';

export const PROFILE_FREE_AETH = 'PROFILE_FREE_AETH';
export const PROFILE_FREE_AETH_ERROR = 'PROFILE_FREE_AETH_ERROR';
export const PROFILE_FREE_AETH_SUCCESS = 'PROFILE_FREE_AETH_SUCCESS';

export const PROFILE_GET_BY_ADDRESS = 'PROFILE_GET_BY_ADDRESS';
export const PROFILE_GET_BY_ADDRESS_ERROR = 'PROFILE_GET_BY_ADDRESS_ERROR';
export const PROFILE_GET_BY_ADDRESS_SUCCESS = 'PROFILE_GET_BY_ADDRESS_SUCCESS';
export const PROFILE_GET_BALANCE = 'PROFILE_GET_BALANCE';
export const PROFILE_GET_BALANCE_ERROR = 'PROFILE_GET_BALANCE_ERROR';
export const PROFILE_GET_BALANCE_SUCCESS = 'PROFILE_GET_BALANCE_SUCCESS';
export const PROFILE_GET_DATA = 'PROFILE_GET_DATA';
export const PROFILE_GET_DATA_ERROR = 'PROFILE_GET_DATA_ERROR';
export const PROFILE_GET_DATA_SUCCESS = 'PROFILE_GET_DATA_SUCCESS';
export const PROFILE_GET_LIST = 'PROFILE_GET_LIST';
export const PROFILE_GET_LIST_ERROR = 'PROFILE_GET_LIST_ERROR';
export const PROFILE_GET_LIST_SUCCESS = 'PROFILE_GET_LIST_SUCCESS';
export const PROFILE_GET_LOCAL = 'PROFILE_GET_LOCAL';
export const PROFILE_GET_LOCAL_ERROR = 'PROFILE_GET_LOCAL_ERROR';
export const PROFILE_GET_LOCAL_SUCCESS = 'PROFILE_GET_LOCAL_SUCCESS';
export const PROFILE_GET_LOGGED = 'PROFILE_GET_LOGGED';
export const PROFILE_GET_LOGGED_ERROR = 'PROFILE_GET_LOGGED_ERROR';
export const PROFILE_GET_LOGGED_SUCCESS = 'PROFILE_GET_LOGGED_SUCCESS';

export const PROFILE_IS_FOLLOWER = 'PROFILE_IS_FOLLOWER';
export const PROFILE_IS_FOLLOWER_ERROR = 'PROFILE_IS_FOLLOWER_ERROR';
export const PROFILE_IS_FOLLOWER_SUCCESS = 'PROFILE_IS_FOLLOWER_SUCCESS';

export const PROFILE_LOGIN = 'PROFILE_LOGIN';
export const PROFILE_LOGIN_ERROR = 'PROFILE_LOGIN_ERROR';
export const PROFILE_LOGIN_SUCCESS = 'PROFILE_LOGIN_SUCCESS';
export const PROFILE_LOGOUT = 'PROFILE_LOGOUT';
export const PROFILE_LOGOUT_ERROR = 'PROFILE_LOGOUT_ERROR';
export const PROFILE_LOGOUT_SUCCESS = 'PROFILE_LOGOUT_SUCCESS';

export const PROFILE_MANA_BURNED = 'PROFILE_MANA_BURNED';
export const PROFILE_MANA_BURNED_ERROR = 'PROFILE_MANA_BURNED_ERROR';
export const PROFILE_MANA_BURNED_SUCCESS = 'PROFILE_MANA_BURNED_SUCCESS';

export const PROFILE_MORE_FOLLOWERS_ITERATOR = 'PROFILE_MORE_FOLLOWERS_ITERATOR';
export const PROFILE_MORE_FOLLOWERS_ITERATOR_ERROR = 'PROFILE_MORE_FOLLOWERS_ITERATOR_ERROR';
export const PROFILE_MORE_FOLLOWERS_ITERATOR_SUCCESS = 'PROFILE_MORE_FOLLOWERS_ITERATOR_SUCCESS';
export const PROFILE_MORE_FOLLOWINGS_ITERATOR = 'PROFILE_MORE_FOLLOWINGS_ITERATOR';
export const PROFILE_MORE_FOLLOWINGS_ITERATOR_ERROR = 'PROFILE_MORE_FOLLOWINGS_ITERATOR_ERROR';
export const PROFILE_MORE_FOLLOWINGS_ITERATOR_SUCCESS = 'PROFILE_MORE_FOLLOWINGS_ITERATOR_SUCCESS';

export const PROFILE_REGISTER = 'PROFILE_REGISTER';
export const PROFILE_REGISTER_ERROR = 'PROFILE_REGISTER_ERROR';
export const PROFILE_REGISTER_SUCCESS = 'PROFILE_REGISTER_SUCCESS';

export const PROFILE_FAUCET = 'PROFILE_FAUCET';
export const PROFILE_FAUCET_ERROR = 'PROFILE_FAUCET_ERROR';
export const PROFILE_FAUCET_SUCCESS = 'PROFILE_FAUCET_SUCCESS';

export const PROFILE_RESET_ESSENCE_EVENTS = 'PROFILE_RESET_ESSENCE_EVENTS';

export const PROFILE_RESOLVE_IPFS_HASH = 'PROFILE_RESOLVE_IPFS_HASH';
export const PROFILE_RESOLVE_IPFS_HASH_ERROR = 'PROFILE_RESOLVE_IPFS_HASH_ERROR';
export const PROFILE_RESOLVE_IPFS_HASH_SUCCESS = 'PROFILE_RESOLVE_IPFS_HASH_SUCCESS';

export const PROFILE_SAVE_AKASHA_IDS_ERROR = 'PROFILE_SAVE_AKASHA_IDS_ERROR';

export const PROFILE_SAVE_LOGGED_ERROR = 'PROFILE_SAVE_LOGGED_ERROR';

export const PROFILE_SEND_TIP = 'PROFILE_SEND_TIP';
export const PROFILE_SEND_TIP_ERROR = 'PROFILE_SEND_TIP_ERROR';
export const PROFILE_SEND_TIP_SUCCESS = 'PROFILE_SEND_TIP_SUCCESS';

export const PROFILE_TOGGLE_INTEREST = 'PROFILE_TOGGLE_INTEREST';

export const PROFILE_TOGGLE_DONATIONS = 'PROFILE_TOGGLE_DONATIONS';
export const PROFILE_TOGGLE_DONATIONS_ERROR = 'PROFILE_TOGGLE_DONATIONS_ERROR';
export const PROFILE_TOGGLE_DONATIONS_SUCCESS = 'PROFILE_TOGGLE_DONATIONS_SUCCESS';

export const PROFILE_TRANSFER_AETH = 'PROFILE_TRANSFER_AETH';
export const PROFILE_TRANSFER_AETH_ERROR = 'PROFILE_TRANSFER_AETH_ERROR';
export const PROFILE_TRANSFER_AETH_SUCCESS = 'PROFILE_TRANSFER_AETH_SUCCESS';
export const PROFILE_TRANSFER_ETH = 'PROFILE_TRANSFER_ETH';
export const PROFILE_TRANSFER_ETH_ERROR = 'PROFILE_TRANSFER_ETH_ERROR';
export const PROFILE_TRANSFER_ETH_SUCCESS = 'PROFILE_TRANSFER_ETH_SUCCESS';

export const PROFILE_TRANSFORM_ESSENCE = 'PROFILE_TRANSFORM_ESSENCE';
export const PROFILE_TRANSFORM_ESSENCE_ERROR = 'PROFILE_TRANSFORM_ESSENCE_ERROR';
export const PROFILE_TRANSFORM_ESSENCE_SUCCESS = 'PROFILE_TRANSFORM_ESSENCE_SUCCESS';

export const PROFILE_UNFOLLOW = 'PROFILE_UNFOLLOW';
export const PROFILE_UNFOLLOW_ERROR = 'PROFILE_UNFOLLOW_ERROR';
export const PROFILE_UNFOLLOW_SUCCESS = 'PROFILE_UNFOLLOW_SUCCESS';

export const PROFILE_UPDATE_LOGGED_ERROR = 'PROFILE_UPDATE_LOGGED_ERROR';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';

export const PUBLISH_CONFIRM_DIALOG_TOGGLE = 'PUBLISH_CONFIRM_DIALOG_TOGGLE';

export const SEARCH_MORE_PROFILES = 'SEARCH_MORE_PROFILES';
export const SEARCH_MORE_PROFILES_ERROR = 'SEARCH_MORE_PROFILES_ERROR';
export const SEARCH_MORE_PROFILES_SUCCESS = 'SEARCH_MORE_PROFILES_SUCCESS';

export const SEARCH_MORE_QUERY = 'SEARCH_MORE_QUERY';
export const SEARCH_MORE_QUERY_ERROR = 'SEARCH_MORE_QUERY_ERROR';
export const SEARCH_MORE_QUERY_SUCCESS = 'SEARCH_MORE_QUERY_SUCCESS';

export const SEARCH_PROFILES = 'SEARCH_PROFILES';
export const SEARCH_PROFILES_ERROR = 'SEARCH_PROFILES_ERROR';
export const SEARCH_PROFILES_SUCCESS = 'SEARCH_PROFILES_SUCCESS';

export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_QUERY_SUCCESS = 'SEARCH_QUERY_SUCCESS';
export const SEARCH_QUERY_ERROR = 'SEARCH_QUERY_ERROR';

export const SEARCH_RESET_RESULTS = 'SEARCH_RESET_RESULTS';

export const SEARCH_SYNC_ENTRIES = 'SEARCH_SYNC_ENTRIES';
export const SEARCH_SYNC_ENTRIES_ERROR = 'SEARCH_SYNC_ENTRIES_ERROR';
export const SEARCH_SYNC_ENTRIES_SUCCESS = 'SEARCH_SYNC_ENTRIES_SUCCESS';

export const SEARCH_SYNC_TAGS = 'SEARCH_SYNC_TAGS';
export const SEARCH_SYNC_TAGS_ERROR = 'SEARCH_SYNC_TAGS_ERROR';
export const SEARCH_SYNC_TAGS_SUCCESS = 'SEARCH_SYNC_TAGS_SUCCESS';

export const SEARCH_TAGS = 'SEARCH_TAGS';
export const SEARCH_TAGS_ERROR = 'SEARCH_TAGS_ERROR';
export const SEARCH_TAGS_SUCCESS = 'SEARCH_TAGS_SUCCESS';

export const SET_TEMP_PROFILE = 'SET_TEMP_PROFILE';

// this should be removed once profile logout is implemented
export const RESET_HOME_READY = 'RESET_HOME_READY';

export const SAVE_CONFIGURATION = 'SAVE_CONFIGURATION';
export const SECONDARY_SIDEBAR_TOGGLE = 'SECONDARY_SIDEBAR_TOGGLE';
export const SERVICES_SET_TIMESTAMP = 'SERVICES_SET_TIMESTAMP';

export const SHOW_REPORT_MODAL = 'SHOW_REPORT_MODAL';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const SHOW_TERMS = 'SHOW_TERMS';

export const TAG_CREATE = 'TAG_CREATE';
export const TAG_CREATE_ERROR = 'TAG_CREATE_ERROR';
export const TAG_CREATE_SUCCESS = 'TAG_CREATE_SUCCESS';
export const TAG_EXISTS = 'TAG_EXISTS';
export const TAG_EXISTS_ERROR = 'TAG_EXISTS_ERROR';
export const TAG_EXISTS_SUCCESS = 'TAG_EXISTS_SUCCESS';
export const TAG_GET_ENTRIES_COUNT = 'TAG_GET_ENTRIES_COUNT';
export const TAG_GET_ENTRIES_COUNT_ERROR = 'TAG_GET_ENTRIES_COUNT_ERROR';
export const TAG_GET_ENTRIES_COUNT_SUCCESS = 'TAG_GET_ENTRIES_COUNT_SUCCESS';
export const TAG_SEARCH = 'TAG_SEARCH';
export const TAG_SEARCH_ERROR = 'TAG_SEARCH_ERROR';
export const TAG_SEARCH_SUCCESS = 'TAG_SEARCH_SUCCESS';
export const TAG_SEARCH_CLEAR = 'TAG_SEARCH_CLEAR';

export const TEMP_PROFILE_CREATE = 'TEMP_PROFILE_CREATE';
export const TEMP_PROFILE_CREATE_SUCCESS = 'TEMP_PROFILE_CREATE_SUCCESS';
export const TEMP_PROFILE_CREATE_ERROR = 'TEMP_PROFILE_CREATE_ERROR';

export const TEMP_PROFILE_DELETE = 'TEMP_PROFILE_DELETE';

export const TEMP_PROFILE_ERROR = 'TEMP_PROFILE_ERROR';

export const TEMP_PROFILE_GET = 'TEMP_PROFILE_GET';
export const TEMP_PROFILE_GET_SUCCESS = 'TEMP_PROFILE_GET_SUCCESS';
export const TEMP_PROFILE_GET_ERROR = 'TEMP_PROFILE_GET_ERROR';

export const TEMP_PROFILE_GET_REQUEST = 'TEMP_PROFILE_REQUEST';

export const TEMP_PROFILE_UPDATE = 'TEMP_PROFILE_UPDATE';
export const TEMP_PROFILE_UPDATE_SUCCESS = 'TEMP_PROFILE_UPDATE_SUCCESS';
export const TEMP_PROFILE_UPDATE_ERROR = 'TEMP_PROFILE_UPDATE_ERROR';

// used to update temp profile (skipping steps from create temp profile);
export const UPDATE_TEMP_PROFILE = 'UPDATE_TEMP_PROFILE';

export const TOGGLE_AETH_WALLET = 'TOGGLE_AETH_WALLET';
export const TOGGLE_ETH_WALLET = 'TOGGLE_ETH_WALLET';
export const TOGGLE_GETH_DETAILS_MODAL = 'TOGGLE_GETH_DETAILS_MODAL';
export const TOGGLE_IPFS_DETAILS_MODAL = 'TOGGLE_IPFS_DETAILS_MODAL';
export const TOGGLE_OUTSIDE_NAVIGATION_MODAL = 'TOGGLE_OUTSIDE_NAVIGATION_MODAL';
export const TRANSACTION_ADD_TO_QUEUE = 'TRANSACTION_ADD_TO_QUEUE';
export const TRANSACTION_ADD_TO_QUEUE_ERROR = 'TRANSACTION_ADD_TO_QUEUE_ERROR';
export const TRANSACTION_ADD_TO_QUEUE_SUCCESS = 'TRANSACTION_ADD_TO_QUEUE_SUCCESS';
export const TRANSACTION_EMIT_MINED_ERROR = 'TRANSACTION_EMIT_MINED_ERROR';
export const TRANSACTION_GET_STATUS = 'TRANSACTION_GET_STATUS';
export const TRANSACTION_GET_STATUS_ERROR = 'TRANSACTION_GET_STATUS_ERROR';
export const TRANSACTION_GET_STATUS_SUCCESS = 'TRANSACTION_GET_STATUS_SUCCESS';

export const TRANSFER_CONFIRM_DIALOG_TOGGLE = 'TRANSFER_CONFIRM_DIALOG_TOGGLE';

export const USER_SETTINGS_CLEAR = 'USER_SETTINGS_CLEAR';
export const USER_SETTINGS_REQUEST = 'USER_SETTINGS_REQUEST';
export const USER_SETTINGS_ERROR = 'USER_SETTINGS_ERROR';
export const USER_SETTINGS_SAVE = 'USER_SETTINGS_SAVE';
export const USER_SETTINGS_SAVE_ERROR = 'USER_SETTINGS_SAVE_ERROR';
export const USER_SETTINGS_SAVE_SUCCESS = 'USER_SETTINGS_SAVE_SUCCESS';
export const USER_SETTINGS_SUCCESS = 'USER_SETTINGS_SUCCESS';

export const WEIGHT_CONFIRM_DIALOG_TOGGLE = 'WEIGHT_CONFIRM_DIALOG_TOGGLE';

export const FEED_SUBSCRIPTION_NOTIF = 'FEED_SUBSCRIPTION_NOTIF';
export const READ_SUBSCRIPTION_NOTIF = 'READ_SUBSCRIPTION_NOTIF';

export const FEED_YOU_NOTIF = 'FEED_YOU_NOTIF';
export const READ_YOU_NOTIF = 'READ_YOU_NOTIF';

export const DELETE_YOU_NOTIF = 'DELETE_YOU_NOTIF';
export const DELETE_FEED_NOTIF = 'DELETE_FEED_NOTIF';
