export const APP_READY = 'APP_READY';

export const BACKUP_KEYS_ERROR = 'BACKUP_KEYS_ERROR';
export const BACKUP_KEYS_REQUEST = 'BACKUP_KEYS_REQUEST';
export const BACKUP_KEYS_SUCCESS = 'BACKUP_KEYS_SUCCESS';

export const BOOTSTRAP_HOME = 'BOOTSTRAP_HOME';
export const BOOTSTRAP_HOME_SUCCESS = 'BOOTSTRAP_HOME_SUCCESS';

export const CLEAR_SYNC_STATUS = 'CLEAR_SYNC_STATUS';

export const COMMENTS_ADD_PUBLISH_ACTION = 'COMMENTS_ADD_PUBLISH_ACTION';
export const COMMENTS_CHECK_NEW = 'COMMENTS_CHECK_NEW';
export const COMMENTS_CHECK_NEW_ERROR = 'COMMENTS_CHECK_NEW_ERROR';
export const COMMENTS_CHECK_NEW_SUCCESS = 'COMMENTS_CHECK_NEW_SUCCESS';
export const COMMENTS_CLEAN = 'COMMENTS_CLEAN';
export const COMMENTS_GET_COUNT = 'COMMENTS_GET_COUNT';
export const COMMENTS_GET_COUNT_ERROR = 'COMMENTS_GET_COUNT_ERROR';
export const COMMENTS_GET_COUNT_SUCCESS = 'COMMENTS_GET_COUNT_SUCCESS';
export const COMMENTS_ITERATOR = 'COMMENTS_ITERATOR';
export const COMMENTS_ITERATOR_ERROR = 'COMMENTS_ITERATOR_ERROR';
export const COMMENTS_ITERATOR_SUCCESS = 'COMMENTS_ITERATOR_SUCCESS';
export const COMMENTS_LOAD_NEW = 'COMMENTS_LOAD_NEW';
export const COMMENTS_MORE_ITERATOR = 'COMMENTS_MORE_ITERATOR';
export const COMMENTS_MORE_ITERATOR_ERROR = 'COMMENTS_MORE_ITERATOR_ERROR';
export const COMMENTS_MORE_ITERATOR_SUCCESS = 'COMMENTS_MORE_ITERATOR_SUCCESS';
export const COMMENTS_PUBLISH = 'COMMENTS_PUBLISH';
export const COMMENTS_PUBLISH_ERROR = 'COMMENTS_PUBLISH_ERROR';
export const COMMENTS_PUBLISH_SUCCESS = 'COMMENTS_PUBLISH_SUCCESS';

export const DASHBOARD_ADD = 'DASHBOARD_ADD';
export const DASHBOARD_ADD_ERROR = 'DASHBOARD_ADD_ERROR';
export const DASHBOARD_ADD_SUCCESS = 'DASHBOARD_ADD_SUCCESS';
export const DASHBOARD_ADD_COLUMN = 'DASHBOARD_ADD_COLUMN';
export const DASHBOARD_ADD_COLUMN_ERROR = 'DASHBOARD_ADD_COLUMN_ERROR';
export const DASHBOARD_ADD_COLUMN_SUCCESS = 'DASHBOARD_ADD_COLUMN_SUCCESS';
export const DASHBOARD_DELETE = 'DASHBOARD_DELETE';
export const DASHBOARD_DELETE_ERROR = 'DASHBOARD_DELETE_ERROR';
export const DASHBOARD_DELETE_SUCCESS = 'DASHBOARD_DELETE_SUCCESS';
export const DASHBOARD_DELETE_COLUMN = 'DASHBOARD_DELETE_COLUMN';
export const DASHBOARD_DELETE_COLUMN_ERROR = 'DASHBOARD_DELETE_COLUMN_ERROR';
export const DASHBOARD_DELETE_COLUMN_SUCCESS = 'DASHBOARD_DELETE_COLUMN_SUCCESS';
export const DASHBOARD_GET_ACTIVE_ERROR = 'DASHBOARD_GET_ACTIVE_ERROR';
export const DASHBOARD_GET_ACTIVE_SUCCESS = 'DASHBOARD_GET_ACTIVE_SUCCESS';
export const DASHBOARD_GET_ALL_ERROR = 'DASHBOARD_GET_ALL_ERROR';
export const DASHBOARD_GET_ALL_SUCCESS = 'DASHBOARD_GET_ALL_SUCCESS';
export const DASHBOARD_GET_COLUMNS_ERROR = 'DASHBOARD_GET_COLUMNS_ERROR';
export const DASHBOARD_GET_COLUMNS_SUCCESS = 'DASHBOARD_GET_COLUMNS_SUCCESS';
export const DASHBOARD_SET_ACTIVE = 'DASHBOARD_SET_ACTIVE';
export const DASHBOARD_SET_ACTIVE_ERROR = 'DASHBOARD_SET_ACTIVE_ERROR';
export const DASHBOARD_SET_ACTIVE_SUCCESS = 'DASHBOARD_SET_ACTIVE_SUCCESS';
export const DASHBOARD_UPDATE_COLUMN = 'DASHBOARD_UPDATE_COLUMN';
export const DASHBOARD_UPDATE_COLUMN_ERROR = 'DASHBOARD_UPDATE_COLUMN_ERROR';
export const DASHBOARD_UPDATE_COLUMN_SUCCESS = 'DASHBOARD_UPDATE_COLUMN_SUCCESS';

export const DELETE_PENDING_ACTION = 'DELETE_PENDING_ACTION';

export const ENTRY_ADD_CLAIM_ACTION = 'ADD_CLAIM_ACTION';
export const ENTRY_ADD_DOWNVOTE_ACTION = 'ADD_DOWNVOTE_ACTION';
export const ENTRY_ADD_UPVOTE_ACTION = 'ADD_UPVOTE_ACTION';

export const ENTRY_CAN_CLAIM = 'ENTRY_CAN_CLAIM';
export const ENTRY_CAN_CLAIM_ERROR = 'ENTRY_CAN_CLAIM_ERROR';
export const ENTRY_CAN_CLAIM_SUCCESS = 'ENTRY_CAN_CLAIM_SUCCESS';
export const ENTRY_CLAIM = 'ENTRY_CLAIM';
export const ENTRY_CLAIM_ERROR = 'ENTRY_CLAIM_ERROR';
export const ENTRY_CLAIM_SUCCESS = 'ENTRY_CLAIM_SUCCESS';
export const ENTRY_CLEAN_FULL = 'ENTRY_CLEAN_FULL';

export const ENTRY_DOWNVOTE = 'ENTRY_DOWNVOTE';
export const ENTRY_DOWNVOTE_ERROR = 'ENTRY_DOWNVOTE_ERROR';
export const ENTRY_DOWNVOTE_SUCCESS = 'ENTRY_DOWNVOTE_SUCCESS';

export const ENTRY_GET_BALANCE = 'ENTRY_GET_BALANCE';
export const ENTRY_GET_BALANCE_ERROR = 'ENTRY_GET_BALANCE_ERROR';
export const ENTRY_GET_BALANCE_SUCCESS = 'ENTRY_GET_BALANCE_SUCCESS';
export const ENTRY_GET_FULL = 'ENTRY_GET_FULL';
export const ENTRY_GET_FULL_ERROR = 'ENTRY_GET_FULL_ERROR';
export const ENTRY_GET_FULL_SUCCESS = 'ENTRY_GET_FULL_SUCCESS';
export const ENTRY_GET_LATEST_VERSION = 'ENTRY_GET_LATEST_VERSION';
export const ENTRY_GET_LATEST_VERSION_ERROR = 'ENTRY_GET_LATEST_VERSION_ERROR';
export const ENTRY_GET_LATEST_VERSION_SUCCESS = 'ENTRY_GET_LATEST_VERSION_SUCCESS';
export const ENTRY_GET_SCORE = 'ENTRY_GET_SCORE';
export const ENTRY_GET_SCORE_ERROR = 'ENTRY_GET_SCORE_ERROR';
export const ENTRY_GET_SCORE_SUCCESS = 'ENTRY_GET_SCORE_SUCCESS';
export const ENTRY_GET_VOTE_OF = 'ENTRY_GET_VOTE_OF';
export const ENTRY_GET_VOTE_OF_ERROR = 'ENTRY_GET_VOTE_OF_ERROR';
export const ENTRY_GET_VOTE_OF_SUCCESS = 'ENTRY_GET_VOTE_OF_SUCCESS';

export const ENTRY_IS_ACTIVE = 'ENTRY_IS_ACTIVE';
export const ENTRY_IS_ACTIVE_ERROR = 'ENTRY_IS_ACTIVE_ERROR';
export const ENTRY_IS_ACTIVE_SUCCESS = 'ENTRY_IS_ACTIVE_SUCCESS';

export const ENTRY_MORE_NEWEST_ITERATOR = 'ENTRY_MORE_NEWEST_ITERATOR';
export const ENTRY_MORE_NEWEST_ITERATOR_ERROR = 'ENTRY_MORE_NEWEST_ITERATOR_ERROR';
export const ENTRY_MORE_NEWEST_ITERATOR_SUCCESS = 'ENTRY_MORE_NEWEST_ITERATOR_SUCCESS';
export const ENTRY_MORE_PROFILE_ITERATOR = 'ENTRY_MORE_PROFILE_ITERATOR';
export const ENTRY_MORE_PROFILE_ITERATOR_ERROR = 'ENTRY_MORE_PROFILE_ITERATOR_ERROR';
export const ENTRY_MORE_PROFILE_ITERATOR_SUCCESS = 'ENTRY_MORE_PROFILE_ITERATOR_SUCCESS';
export const ENTRY_MORE_STREAM_ITERATOR = 'ENTRY_MORE_STREAM_ITERATOR';
export const ENTRY_MORE_STREAM_ITERATOR_ERROR = 'ENTRY_MORE_STREAM_ITERATOR_ERROR';
export const ENTRY_MORE_STREAM_ITERATOR_SUCCESS = 'ENTRY_MORE_STREAM_ITERATOR_SUCCESS';
export const ENTRY_MORE_TAG_ITERATOR = 'ENTRY_MORE_TAG_ITERATOR';
export const ENTRY_MORE_TAG_ITERATOR_ERROR = 'ENTRY_MORE_TAG_ITERATOR_ERROR';
export const ENTRY_MORE_TAG_ITERATOR_SUCCESS = 'ENTRY_MORE_TAG_ITERATOR_SUCCESS';

export const ENTRY_NEWEST_ITERATOR = 'ENTRY_NEWEST_ITERATOR';
export const ENTRY_NEWEST_ITERATOR_ERROR = 'ENTRY_NEWEST_ITERATOR_ERROR';
export const ENTRY_NEWEST_ITERATOR_SUCCESS = 'ENTRY_NEWEST_ITERATOR_SUCCESS';

export const ENTRY_PAGE_HIDE = 'ENTRY_PAGE_HIDE';
export const ENTRY_PAGE_SHOW = 'ENTRY_PAGE_SHOW';

export const ENTRY_PROFILE_ITERATOR = 'ENTRY_PROFILE_ITERATOR';
export const ENTRY_PROFILE_ITERATOR_ERROR = 'ENTRY_PROFILE_ITERATOR_ERROR';
export const ENTRY_PROFILE_ITERATOR_SUCCESS = 'ENTRY_PROFILE_ITERATOR_SUCCESS';

export const ENTRY_STREAM_ITERATOR = 'ENTRY_STREAM_ITERATOR';
export const ENTRY_STREAM_ITERATOR_ERROR = 'ENTRY_STREAM_ITERATOR_ERROR';
export const ENTRY_STREAM_ITERATOR_SUCCESS = 'ENTRY_STREAM_ITERATOR_SUCCESS';

export const ENTRY_UPVOTE = 'ENTRY_UPVOTE';
export const ENTRY_UPVOTE_ERROR = 'ENTRY_UPVOTE_ERROR';
export const ENTRY_UPVOTE_SUCCESS = 'ENTRY_UPVOTE_SUCCESS';

export const ENTRY_TAG_ITERATOR = 'ENTRY_TAG_ITERATOR';
export const ENTRY_TAG_ITERATOR_ERROR = 'ENTRY_TAG_ITERATOR_ERROR';
export const ENTRY_TAG_ITERATOR_SUCCESS = 'ENTRY_TAG_ITERATOR_SUCCESS';

export const ENTRY_VOTE_COST = 'ENTRY_VOTE_COST';
export const ENTRY_VOTE_COST_ERROR = 'ENTRY_VOTE_COST_ERROR';
export const ENTRY_VOTE_COST_SUCCESS = 'ENTRY_VOTE_COST_SUCCESS';

export const ERROR_DELETE_FATAL = 'ERROR_DELETE_FATAL';
export const ERROR_DELETE_NON_FATAL = 'ERROR_DELETE_NON_FATAL';

export const ETH_ADDRESS_CREATE = 'ETH_ADDRESS_CREATE';
export const ETH_ADDRESS_CREATE_SUCCESS = 'ETH_ADDRESS_CREATE_SUCCESS';
export const ETH_ADDRESS_CREATE_ERROR = 'ETH_ADDRESS_CREATE_ERROR';

export const FUND_FROM_FAUCET = 'FUND_FROM_FAUCET';
export const FUND_FROM_FAUCET_SUCCESS = 'FUND_FROM_FAUCET_SUCCESS';
export const FUND_FROM_FAUCET_ERROR = 'FUND_FROM_FAUCET_ERROR';

export const FAUCET_TX_MINED_SUCCESS = 'FAUCET_TX_MINED_SUCCESS';
export const FAUCET_TX_MINED_ERROR = 'FAUCET_TX_MINED_ERROR';

export const GENERAL_SETTINGS = 'GENERAL_SETTINGS';
export const GENERAL_SETTINGS_ERROR = 'GENERAL_SETTINGS_ERROR';
export const GENERAL_SETTINGS_SUCCESS = 'GENERAL_SETTINGS_SUCCESS';
export const GENERAL_SETTINGS_SAVE = 'GENERAL_SETTINGS_SAVE';
export const GENERAL_SETTINGS_SAVE_ERROR = 'GENERAL_SETTINGS_SAVE_ERROR';
export const GENERAL_SETTINGS_SAVE_SUCCESS = 'GENERAL_SETTINGS_SAVE_SUCCESS';

export const GETH_GET_LOGS = 'GETH_GET_LOGS';
export const GETH_GET_LOGS_SUCCESS = 'GETH_GET_LOGS_SUCCESS';
export const GETH_GET_OPTIONS_ERROR = 'GETH_GET_OPTIONS_ERROR';
export const GETH_GET_OPTIONS_SUCCESS = 'GETH_GET_OPTIONS_SUCCESS';
export const GETH_GET_STATUS = 'GETH_GET_STATUS';
export const GETH_GET_STATUS_ERROR = 'GETH_GET_STATUS_ERROR';
export const GETH_GET_STATUS_SUCCESS = 'GETH_GET_STATUS_SUCCESS';
export const GETH_GET_SYNC_STATUS = 'GETH_GET_SYNC_STATUS';
export const GETH_GET_SYNC_STATUS_ERROR = 'GETH_GET_SYNC_STATUS_ERROR';
export const GETH_GET_SYNC_STATUS_SUCCESS = 'GETH_GET_SYNC_STATUS_SUCCESS';
export const GETH_PAUSE_SYNC = 'GETH_PAUSE_SYNC';
export const GETH_RESET_BUSY = 'GETH_RESET_BUSY';
export const GETH_RESUME_SYNC = 'GETH_RESUME_SYNC';
export const GETH_SAVE_SETTINGS = 'GETH_SAVE_SETTINGS';
export const GETH_SAVE_SETTINGS_ERROR = 'GETH_SAVE_SETTINGS_ERROR';
export const GETH_SAVE_SETTINGS_SUCCESS = 'GETH_SAVE_SETTINGS_SUCCESS';
export const GETH_SETTINGS = 'GETH_SETTINGS';
export const GETH_SETTINGS_ERROR = 'GETH_SETTINGS_ERROR';
export const GETH_SETTINGS_SUCCESS = 'GETH_SETTINGS_SUCCESS';
export const GETH_START = 'GETH_START';
export const GETH_START_ERROR = 'GETH_START_ERROR';
export const GETH_START_LOGGER = 'GETH_START_LOGGER';
export const GETH_START_SUCCESS = 'GETH_START_SUCCESS';
export const GETH_STOP = 'GETH_STOP';
export const GETH_STOP_ERROR = 'GETH_STOP_ERROR';
export const GETH_STOP_LOGGER = 'GETH_STOP_LOGGER';
export const GETH_STOP_SUCCESS = 'GETH_STOP_SUCCESS';
export const GETH_STOP_SYNC = 'GETH_STOP_SYNC';

export const HIDE_AUTH_DIALOG = 'HIDE_AUTH_DIALOG';
export const HIDE_LOGIN_DIALOG = 'HIDE_LOGIN_DIALOG';
export const HIDE_REPORT_MODAL = 'HIDE_REPORT_MODAL';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const HIDE_TERMS = 'HIDE_TERMS';
export const HIDE_WEIGHT_CONFIRM_DIALOG = 'HIDE_WEIGHT_CONFIRM_DIALOG';

export const IPFS_GET_CONFIG_ERROR = 'IPFS_GET_CONFIG_ERROR';
export const IPFS_GET_CONFIG_SUCCESS = 'IPFS_GET_CONFIG_SUCCESS';
export const IPFS_GET_LOGS = 'IPFS_GET_LOGS';
export const IPFS_GET_LOGS_SUCCESS = 'IPFS_GET_LOGS_SUCCESS';
export const IPFS_GET_PORTS = 'IPFS_GET_PORTS';
export const IPFS_GET_PORTS_ERROR = 'IPFS_GET_PORTS_ERROR';
export const IPFS_GET_PORTS_SUCCESS = 'IPFS_GET_PORTS_SUCCESS';
export const IPFS_GET_STATUS = 'IPFS_GET_STATUS';
export const IPFS_GET_STATUS_ERROR = 'IPFS_GET_STATUS_ERROR';
export const IPFS_GET_STATUS_SUCCESS = 'IPFS_GET_STATUS_SUCCESS';
export const IPFS_RESET_BUSY = 'IPFS_RESET_BUSY';
export const IPFS_RESET_PORTS = 'IPFS_RESET_PORTS';
export const IPFS_SAVE_SETTINGS = 'IPFS_SAVE_SETTINGS';
export const IPFS_SAVE_SETTINGS_ERROR = 'IPFS_SAVE_SETTINGS_ERROR';
export const IPFS_SAVE_SETTINGS_SUCCESS = 'IPFS_SAVE_SETTINGS_SUCCESS';
export const IPFS_SET_PORTS = 'IPFS_SET_PORTS';
export const IPFS_SET_PORTS_ERROR = 'IPFS_SET_PORTS_ERROR';
export const IPFS_SET_PORTS_SUCCESS = 'IPFS_SET_PORTS_SUCCESS';
export const IPFS_SETTINGS = 'IPFS_SETTINGS';
export const IPFS_SETTINGS_ERROR = 'IPFS_SETTINGS_ERROR';
export const IPFS_SETTINGS_SUCCESS = 'IPFS_SETTINGS_SUCCESS';
export const IPFS_START = 'IPFS_START';
export const IPFS_START_ERROR = 'IPFS_START_ERROR';
export const IPFS_START_LOGGER = 'IPFS_START_LOGGER';
export const IPFS_START_SUCCESS = 'IPFS_START_SUCCESS';
export const IPFS_STOP = 'IPFS_STOP';
export const IPFS_STOP_ERROR = 'IPFS_STOP_ERROR';
export const IPFS_STOP_LOGGER = 'IPFS_STOP_LOGGER';
export const IPFS_STOP_SUCCESS = 'IPFS_STOP_SUCCESS';

export const LICENSE_GET_ALL = 'LICENSE_GET_ALL';
export const LICENSE_GET_ALL_ERROR = 'LICENSE_GET_ALL_ERROR';
export const LICENSE_GET_ALL_SUCCESS = 'LICENSE_GET_ALL_SUCCESS';

export const LISTEN_FAUCET_TX = 'LISTEN_FAUCET_TX';
export const LISTEN_PUBLISH_TX = 'LISTEN_PUBLISH_TX';

export const PANEL_HIDE = 'PANEL_HIDE';
export const PANEL_SHOW = 'PANEL_SHOW';

export const PROFILE_CLEAR_LOCAL = 'PROFILE_CLEAR_LOCAL';
export const PROFILE_CLEAR_LOGIN_ERRORS = 'PROFILE_CLEAR_LOGIN_ERRORS';

export const PROFILE_DELETE_LOGGED = 'PROFILE_DELETE_LOGGED';
export const PROFILE_DELETE_LOGGED_ERROR = 'PROFILE_DELETE_LOGGED_ERROR';
export const PROFILE_DELETE_LOGGED_SUCCESS = 'PROFILE_DELETE_LOGGED_SUCCESS';

export const PROFILE_GET_BALANCE = 'PROFILE_GET_BALANCE';
export const PROFILE_GET_BALANCE_ERROR = 'PROFILE_GET_BALANCE_ERROR';
export const PROFILE_GET_BALANCE_SUCCESS = 'PROFILE_GET_BALANCE_SUCCESS';
export const PROFILE_GET_CURRENT = 'PROFILE_GET_CURRENT';
export const PROFILE_GET_CURRENT_ERROR = 'PROFILE_GET_CURRENT_ERROR';
export const PROFILE_GET_CURRENT_SUCCESS = 'PROFILE_GET_CURRENT_SUCCESS';
export const PROFILE_GET_DATA = 'PROFILE_GET_DATA';
export const PROFILE_GET_DATA_ERROR = 'PROFILE_GET_DATA_ERROR';
export const PROFILE_GET_DATA_SUCCESS = 'PROFILE_GET_DATA_SUCCESS';
export const PROFILE_GET_LIST = 'PROFILE_GET_LIST';
export const PROFILE_GET_LIST_ERROR = 'PROFILE_GET_LIST_ERROR';
export const PROFILE_GET_LIST_SUCCESS = 'PROFILE_GET_LIST_SUCCESS';
export const PROFILE_GET_LOCAL = 'PROFILE_GET_LOCAL';
export const PROFILE_GET_LOCAL_ERROR = 'PROFILE_GET_LOCAL_ERROR';
export const PROFILE_GET_LOCAL_SUCCESS = 'PROFILE_GET_LOCAL_SUCCESS';
export const PROFILE_GET_LOGGED = 'PROFILE_GET_LOGGED';
export const PROFILE_GET_LOGGED_ERROR = 'PROFILE_GET_LOGGED_ERROR';
export const PROFILE_GET_LOGGED_SUCCESS = 'PROFILE_GET_LOGGED_SUCCESS';

export const PROFILE_LOGIN = 'PROFILE_LOGIN';
export const PROFILE_LOGIN_ERROR = 'PROFILE_LOGIN_ERROR';
export const PROFILE_LOGIN_SUCCESS = 'PROFILE_LOGIN_SUCCESS';
export const PROFILE_LOGOUT = 'PROFILE_LOGOUT';
export const PROFILE_LOGOUT_ERROR = 'PROFILE_LOGOUT_ERROR';
export const PROFILE_LOGOUT_SUCCESS = 'PROFILE_LOGOUT_SUCCESS';

export const PROFILE_SAVE_LOGGED_ERROR = 'PROFILE_SAVE_LOGGED_ERROR';

// this should be removed once profile logout is implemented
export const RESET_HOME_READY = 'RESET_HOME_READY';

export const SAVE_CONFIGURATION = 'SAVE_CONFIGURATION';

export const SERVICES_SET_TIMESTAMP = 'SERVICES_SET_TIMESTAMP';

export const SHOW_AUTH_DIALOG = 'SHOW_AUTH_DIALOG';
export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG';
export const SHOW_REPORT_MODAL = 'SHOW_REPORT_MODAL';
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const SHOW_PUBLISH_CONFIRM_DIALOG = 'SHOW_PUBLISH_CONFIRM_DIALOG';
export const SHOW_TERMS = 'SHOW_TERMS';
export const SHOW_TRANSFER_CONFIRM_DIALOG = 'SHOW_TRANSFER_CONFIRM_DIALOG';
export const SHOW_WEIGHT_CONFIRM_DIALOG = 'SHOW_WEIGHT_CONFIRM_DIALOG';

export const TAG_GET_MARGINS_ERROR = 'TAG_GET_MARGINS_ERROR';
export const TAG_GET_MARGINS_SUCCESS = 'TAG_GET_MARGINS_SUCCESS';
export const TAG_GET_SUGGESTIONS = 'TAG_GET_SUGGESTIONS';
export const TAG_GET_SUGGESTIONS_ERROR = 'TAG_GET_SUGGESTIONS_ERROR';
export const TAG_GET_SUGGESTIONS_SUCCESS = 'TAG_GET_SUGGESTIONS_SUCCESS';
export const TAG_ITERATOR = 'TAG_ITERATOR';
export const TAG_ITERATOR_ERROR = 'TAG_ITERATOR_ERROR';
export const TAG_SAVE = 'TAG_SAVE';
export const TAG_SAVE_ERROR = 'TAG_SAVE_ERROR';
export const TAG_SAVE_SUCCESS = 'TAG_SAVE_SUCCESS';

export const TEMP_PROFILE_ABORT = 'TEMP_PROFILE_ABORT';
export const TEMP_PROFILE_ABORT_SUCCESS = 'TEMP_PROFILE_ABORT_SUCCESS';
export const TEMP_PROFILE_ABORT_ERROR = 'TEMP_PROFILE_ABORT_ERROR';

export const TEMP_PROFILE_CREATE = 'TEMP_PROFILE_CREATE';
export const TEMP_PROFILE_CREATE_SUCCESS = 'TEMP_PROFILE_CREATE_SUCCESS';
export const TEMP_PROFILE_CREATE_ERROR = 'TEMP_PROFILE_CREATE_ERROR';

export const TEMP_PROFILE_DELETE = 'TEMP_PROFILE_DELETE';
export const TEMP_PROFILE_DELETE_SUCCESS = 'TEMP_PROFILE_DELETE_SUCCESS';
export const TEMP_PROFILE_DELETE_ERROR = 'TEMP_PROFILE_DELETE_ERROR';

export const TEMP_PROFILE_STATUS_RESET = 'TEMP_PROFILE_STATUS_RESET';

export const TEMP_PROFILE_ERROR = 'TEMP_PROFILE_ERROR';

export const TEMP_PROFILE_FAUCET_TX_MINED = 'TEMP_PROFILE_FAUCET_TX_MINED';
export const TEMP_PROFILE_FAUCET_TX_MINED_SUCCESS = 'TEMP_PROFILE_FAUCET_TX_MINED_SUCCESS';

export const TEMP_PROFILE_GET = 'TEMP_PROFILE_GET';
export const TEMP_PROFILE_GET_SUCCESS = 'TEMP_PROFILE_GET_SUCCESS';
export const TEMP_PROFILE_GET_ERROR = 'TEMP_PROFILE_GET_ERROR';

export const TEMP_PROFILE_LOGIN = 'TEMP_PROFILE_LOGIN';
export const TEMP_PROFILE_LOGIN_SUCCESS = 'TEMP_PROFILE_LOGIN_SUCCESS';
export const TEMP_PROFILE_LOGIN_ERROR = 'TEMP_PROFILE_LOGIN_ERROR';

export const TEMP_PROFILE_PUBLISH = 'TEMP_PROFILE_PUBLISH';
export const TEMP_PROFILE_PUBLISH_SUCCESS = 'TEMP_PROFILE_PUBLISH_SUCCESS';
export const TEMP_PROFILE_PUBLISH_ERROR = 'TEMP_PROFILE_PUBLISH_ERROR';

export const TEMP_PROFILE_PUBLISH_TX_MINED = 'TEMP_PROFILE_PUBLISH_TX_MINED';
export const TEMP_PROFILE_PUBLISH_TX_MINED_SUCCESS = 'TEMP_PROFILE_PUBLISH_TX_MINED_SUCCESS';

export const TEMP_PROFILE_GET_REQUEST = 'TEMP_PROFILE_REQUEST';

export const TEMP_PROFILE_UPDATE = 'TEMP_PROFILE_UPDATE';
export const TEMP_PROFILE_UPDATE_SUCCESS = 'TEMP_PROFILE_UPDATE_SUCCESS';
export const TEMP_PROFILE_UPDATE_ERROR = 'TEMP_PROFILE_UPDATE_ERROR';

export const TOGGLE_GETH_DETAILS_MODAL = 'TOGGLE_GETH_DETAILS_MODAL';
export const TOGGLE_IPFS_DETAILS_MODAL = 'TOGGLE_IPFS_DETAILS_MODAL';

export const TRANSACTION_ADD_TO_QUEUE = 'TRANSACTION_ADD_TO_QUEUE';
export const TRANSACTION_ADD_TO_QUEUE_ERROR = 'TRANSACTION_ADD_TO_QUEUE_ERROR';
export const TRANSACTION_ADD_TO_QUEUE_SUCCESS = 'TRANSACTION_ADD_TO_QUEUE_SUCCESS';
export const TRANSACTION_DELETE_PENDING = 'TRANSACTION_DELETE_PENDING';
export const TRANSACTION_DELETE_PENDING_ERROR = 'TRANSACTION_DELETE_PENDING_ERROR';
export const TRANSACTION_DELETE_PENDING_SUCCESS = 'TRANSACTION_DELETE_PENDING_SUCCESS';
export const TRANSACTION_EMIT_MINED_ERROR = 'TRANSACTION_EMIT_MINED_ERROR';
export const TRANSACTION_EMIT_MINED_SUCCESS = 'TRANSACTION_EMIT_MINED_SUCCESS';
export const TRANSACTION_GET_MINED = 'TRANSACTION_GET_MINED';
export const TRANSACTION_GET_MINED_ERROR = 'TRANSACTION_GET_MINED_ERROR';
export const TRANSACTION_GET_MINED_SUCCESS = 'TRANSACTION_GET_MINED_SUCCESS';
export const TRANSACTION_GET_PENDING = 'TRANSACTION_GET_PENDING';
export const TRANSACTION_GET_PENDING_ERROR = 'TRANSACTION_GET_PENDING_ERROR';
export const TRANSACTION_GET_PENDING_SUCCESS = 'TRANSACTION_GET_PENDING_SUCCESS';
export const TRANSACTION_GET_STATUS = 'TRANSACTION_GET_STATUS';
export const TRANSACTION_GET_STATUS_ERROR = 'TRANSACTION_GET_STATUS_ERROR';
export const TRANSACTION_GET_STATUS_SUCCESS = 'TRANSACTION_GET_STATUS_SUCCESS';
export const TRANSACTION_SAVE_PENDING_ERROR = 'TRANSACTION_SAVE_PENDING_ERROR';

export const UPDATE_ACTION = 'UPDATE_ACTION';

export const USER_SETTINGS_CLEAR = 'USER_SETTINGS_CLEAR';
export const USER_SETTINGS_REQUEST = 'USER_SETTINGS_REQUEST';
export const USER_SETTINGS_ERROR = 'USER_SETTINGS_ERROR';
export const USER_SETTINGS_SAVE = 'USER_SETTINGS_SAVE';
export const USER_SETTINGS_SAVE_ERROR = 'USER_SETTINGS_SAVE_ERROR';
export const USER_SETTINGS_SAVE_SUCCESS = 'USER_SETTINGS_SAVE_SUCCESS';
export const USER_SETTINGS_SUCCESS = 'USER_SETTINGS_SUCCESS';
