export const FEED_SUBSCRIPTION_NOTIF = 'FEED_SUBSCRIPTION_NOTIF';
export const READ_SUBSCRIPTION_NOTIF = 'READ_SUBSCRIPTION_NOTIF';

export const FEED_YOU_NOTIF = 'FEED_YOU_NOTIF';
export const READ_YOU_NOTIF = 'READ_YOU_NOTIF';

export const DELETE_YOU_NOTIF = 'DELETE_YOU_NOTIF';
export const DELETE_FEED_NOTIF = 'DELETE_FEED_NOTIF';
