export const TOGGLE_DETAILS = 'TOGGLE_DETAILS';

export const GET_LOCAL_PROFILES = 'GET_LOCAL_PROFILES';
export const GET_LOCAL_PROFILES_SUCCESS = 'GET_LOCAL_PROFILES_SUCCESS';
export const GET_LOCAL_PROFILES_ERROR = 'GET_LOCAL_PROFILES_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const GET_PROFILE_DATA_FULL = 'GET_PROFILE_DATA_FULL';
export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_ERROR = 'GET_PROFILE_DATA_ERROR';

export const GET_PROFILE_LIST = 'GET_PROFILE_LIST';
export const GET_PROFILE_LIST_SUCCESS = 'GET_PROFILE_LIST_SUCCESS';
export const GET_PROFILE_LIST_ERROR = 'GET_PROFILE_LIST_ERROR';

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';
export const UPDATE_PROFILE_DATA_SUCCESS = 'UPDATE_PROFILE_DATA_SUCCESS';
export const UPDATE_PROFILE_DATA_ERROR = 'UPDATE_PROFILE_DATA_ERROR';

export const CLEAR_LOCAL_PROFILES_SUCCESS = 'CLEAR_LOCAL_PROFILES_SUCCESS';

export const GET_UPDATE_PROFILE_TXS = 'GET_UPDATE_PROFILE_TXS';
export const GET_UPDATE_PROFILE_TXS_SUCCESS = 'GET_UPDATE_PROFILE_TXS_SUCCESS';
export const GET_UPDATE_PROFILE_TXS_ERROR = 'GET_UPDATE_PROFILE_TXS_ERROR';

export const ADD_UPDATE_PROFILE_TX = 'ADD_UPDATE_PROFILE_TX';
export const ADD_UPDATE_PROFILE_TX_SUCCESS = 'ADD_UPDATE_PROFILE_TX_SUCCESS';
export const ADD_UPDATE_PROFILE_TX_ERROR = 'ADD_UPDATE_PROFILE_TX_ERROR';

export const DELETE_UPDATE_PROFILE_TX = 'DELETE_UPDATE_PROFILE_TX';
export const DELETE_UPDATE_PROFILE_TX_SUCCESS = 'DELETE_UPDATE_PROFILE_TX_SUCCESS';
export const DELETE_UPDATE_PROFILE_TX_ERROR = 'DELETE_UPDATE_PROFILE_TX_ERROR';

export const GET_LOGGED_PROFILE = 'GET_LOGGED_PROFILE';
export const GET_LOGGED_PROFILE_SUCCESS = 'GET_LOGGED_PROFILE_SUCCESS';
export const GET_LOGGED_PROFILE_ERROR = 'GET_LOGGED_PROFILE_ERROR';

export const CLEAR_LOGGED_PROFILE_SUCCESS = 'CLEAR_LOGGED_PROFILE_SUCCESS';
export const CLEAR_LOGGED_PROFILE_ERROR = 'CLEAR_LOGGED_PROFILE_ERROR';

export const GET_PROFILE_BALANCE_SUCCESS = 'GET_PROFILE_BALANCE_SUCCESS';
export const GET_PROFILE_BALANCE_ERROR = 'GET_PROFILE_BALANCE_ERROR';

export const CLEAR_PROFILE_ERRORS = 'CLEAR_PROFILE_ERRORS';
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS';

export const GET_CURRENT_PROFILE = 'GET_CURRENT_PROFILE';
export const GET_CURRENT_PROFILE_SUCCESS = 'GET_CURRENT_PROFILE_SUCCESS';
export const GET_CURRENT_PROFILE_ERROR = 'GET_CURRENT_PROFILE_ERROR';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const GET_FOLLOWERS_COUNT = 'GET_FOLLOWERS_COUNT';
export const GET_FOLLOWERS_COUNT_SUCCESS = 'GET_FOLLOWERS_COUNT_SUCCESS';
export const GET_FOLLOWERS_COUNT_ERROR = 'GET_FOLLOWERS_COUNT_ERROR';
export const GET_FOLLOWING_COUNT = 'GET_FOLLOWING_COUNT';
export const GET_FOLLOWING_COUNT_SUCCESS = 'GET_FOLLOWING_COUNT_SUCCESS';
export const GET_FOLLOWING_COUNT_ERROR = 'GET_FOLLOWING_COUNT_ERROR';

export const FOLLOWERS_ITERATOR = 'FOLLOWERS_ITERATOR';
export const FOLLOWERS_ITERATOR_SUCCESS = 'FOLLOWERS_ITERATOR_SUCCESS';
export const FOLLOWERS_ITERATOR_ERROR = 'FOLLOWERS_ITERATOR_ERROR';

export const MORE_FOLLOWERS_ITERATOR = 'MORE_FOLLOWERS_ITERATOR';
export const MORE_FOLLOWERS_ITERATOR_SUCCESS = 'MORE_FOLLOWERS_ITERATOR_SUCCESS';
export const MORE_FOLLOWERS_ITERATOR_ERROR = 'MORE_FOLLOWERS_ITERATOR_ERROR';

export const FOLLOWING_ITERATOR = 'FOLLOWING_ITERATOR';
export const FOLLOWING_ITERATOR_SUCCESS = 'FOLLOWING_ITERATOR_SUCCESS';
export const FOLLOWING_ITERATOR_ERROR = 'FOLLOWING_ITERATOR_ERROR';

export const MORE_FOLLOWING_ITERATOR = 'MORE_FOLLOWING_ITERATOR';
export const MORE_FOLLOWING_ITERATOR_SUCCESS = 'MORE_FOLLOWING_ITERATOR_SUCCESS';
export const MORE_FOLLOWING_ITERATOR_ERROR = 'MORE_FOLLOWING_ITERATOR_ERROR';

export const GET_FOLLOWING = 'GET_FOLLOWING';
export const GET_FOLLOWING_SUCCESS = 'GET_FOLLOWING_SUCCESS';
export const GET_FOLLOWING_ERROR = 'GET_FOLLOWING_ERROR';

export const FOLLOW_PROFILE = 'FOLLOW_PROFILE';
export const FOLLOW_PROFILE_SUCCESS = 'FOLLOW_PROFILE_SUCCESS';
export const FOLLOW_PROFILE_ERROR = 'FOLLOW_PROFILE_ERROR';

export const UNFOLLOW_PROFILE = 'UNFOLLOW_PROFILE';
export const UNFOLLOW_PROFILE_SUCCESS = 'UNFOLLOW_PROFILE_SUCCESS';
export const UNFOLLOW_PROFILE_ERROR = 'UNFOLLOW_PROFILE_ERROR';

export const IS_FOLLOWER = 'IS_FOLLOWER';
export const IS_FOLLOWER_SUCCESS = 'IS_FOLLOWER_SUCCESS';
export const IS_FOLLOWER_ERROR = 'IS_FOLLOWER_ERROR';

export const SEND_TIP = 'SEND_TIP';
export const SEND_TIP_SUCCESS = 'SEND_TIP_SUCCESS';
export const SEND_TIP_ERROR = 'SEND_TIP_ERROR';

export const RESET_FLAGS = 'RESET_FLAGS';

export const CLEAR_OTHER_PROFILES = 'CLEAR_OTHER_PROFILES';

export const CLEAR_FOLLOWERS = 'CLEAR_FOLLOWERS';
export const CLEAR_FOLLOWING = 'CLEAR_FOLLOWING';
