export const TOGGLE_DETAILS = 'TOGGLE_DETAILS';

export const GET_LOCAL_PROFILES = 'GET_LOCAL_PROFILES';
export const GET_LOCAL_PROFILES_SUCCESS = 'GET_LOCAL_PROFILES_SUCCESS';
export const GET_LOCAL_PROFILES_ERROR = 'GET_LOCAL_PROFILES_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const GET_PROFILE_DATA_SUCCESS = 'GET_PROFILE_DATA_SUCCESS';
export const GET_PROFILE_DATA_ERROR = 'GET_PROFILE_DATA_ERROR';
export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';
export const UPDATE_PROFILE_DATA_SUCCESS = 'UPDATE_PROFILE_DATA_SUCCESS';
export const UPDATE_PROFILE_DATA_ERROR = 'UPDATE_PROFILE_DATA_ERROR';
export const CLEAR_LOCAL_PROFILES_SUCCESS = 'CLEAR_LOCAL_PROFILES_SUCCESS';

export const GET_UPDATE_PROFILE_TXS = 'GET_UPDATE_PROFILE_TXS';
export const GET_UPDATE_PROFILE_TXS_SUCCESS = 'GET_UPDATE_PROFILE_TXS_SUCCESS';
export const GET_UPDATE_PROFILE_TXS_ERROR = 'GET_UPDATE_PROFILE_TXS_ERROR';

export const ADD_UPDATE_PROFILE_TX = 'ADD_UPDATE_PROFILE_TX';
export const ADD_UPDATE_PROFILE_TX_SUCCESS = 'ADD_UPDATE_PROFILE_TX_SUCCESS';
export const ADD_UPDATE_PROFILE_TX_ERROR = 'ADD_UPDATE_PROFILE_TX_ERROR';

export const DELETE_UPDATE_PROFILE_TX = 'DELETE_UPDATE_PROFILE_TX';
export const DELETE_UPDATE_PROFILE_TX_SUCCESS = 'DELETE_UPDATE_PROFILE_TX_SUCCESS';
export const DELETE_UPDATE_PROFILE_TX_ERROR = 'DELETE_UPDATE_PROFILE_TX_ERROR';

export const GET_LOGGED_PROFILE = 'GET_LOGGED_PROFILE';
export const GET_LOGGED_PROFILE_SUCCESS = 'GET_LOGGED_PROFILE_SUCCESS';
export const GET_LOGGED_PROFILE_ERROR = 'GET_LOGGED_PROFILE_ERROR';
export const GET_FULL_LOGGED_PROFILE = 'GET_FULL_LOGGED_PROFILE';

export const CLEAR_LOGGED_PROFILE_SUCCESS = 'CLEAR_LOGGED_PROFILE_SUCCESS';
export const CLEAR_LOGGED_PROFILE_ERROR = 'CLEAR_LOGGED_PROFILE_ERROR';

export const GET_PROFILE_BALANCE_SUCCESS = 'GET_PROFILE_BALANCE_SUCCESS';
export const GET_PROFILE_BALANCE_ERROR = 'GET_PROFILE_BALANCE_ERROR';

export const CLEAR_PROFILE_ERRORS = 'CLEAR_PROFILE_ERRORS';

export const GET_CURRENT_PROFILE_SUCCESS = 'GET_CURRENT_PROFILE_SUCCESS';
export const GET_CURRENT_PROFILE_ERROR = 'GET_CURRENT_PROFILE_ERROR';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
