export const HANDSHAKE = 'HANDSHAKE';
export const HANDSHAKE_SUCCESS = 'HANDSHAKE_SUCCESS';
export const HANDSHAKE_ERROR = 'HANDSHAKE_ERROR';

export const QUERY = 'QUERY';
export const QUERY_SUCCESS = 'QUERY_SUCCESS';
export const QUERY_ERROR = 'QUERY_ERROR';

export const MORE_QUERY = 'MORE_QUERY';
export const MORE_QUERY_SUCCESS = 'MORE_QUERY_SUCCESS';
export const MORE_QUERY_ERROR = 'MORE_QUERY_ERROR';

export const RESET_RESULTS = 'RESET_RESULTS';
