export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_SETTINGS_ERROR = 'SAVE_SETTINGS_ERROR';

export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_ERROR = 'GET_SETTINGS_ERROR';

export const GET_USER_SETTINGS_SUCCESS = 'GET_USER_SETTINGS_SUCCESS';
export const GET_USER_SETTINGS_ERROR = 'GET_USER_SETTINGS_ERROR';

export const CLEAN_USER_SETTINGS = 'CLEAN_USER_SETTINGS';

export const START_FETCHING_SETTINGS = 'START_FETCHING_SETTINGS';
export const FINISH_FETCHING_SETTINGS = 'FINISH_FETCHING_SETTINGS';

export const SAVE_USER_SETTINGS = 'SAVE_USER_SETTINGS';
export const SAVE_USER_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_USER_SETTINGS_ERROR = 'SAVE_SETTINGS_ERROR';

export const SAVE_LATEST_MENTION_SUCCESS = 'SAVE_LATEST_MENTION_SUCCESS';
export const SAVE_LATEST_MENTION_ERROR = 'SAVE_LATEST_MENTION_ERROR';

export const SAVE_PASSWORD_PREFERENCE_SUCCESS = 'SAVE_PASSWORD_PREFERENCE_SUCCESS';
export const SAVE_PASSWORD_PREFERENCE_ERROR = 'SAVE_PASSWORD_PREFERENCE_ERROR';

export const RETRY_SETUP = 'RETRY_SETUP';
export const RESET_SETTINGS = 'RESET_SETTINGS';

// general
export const CHANGE_THEME = 'CHANGE_THEME';

