export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_SETTINGS_ERROR = 'SAVE_SETTINGS_ERROR';

export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_ERROR = 'GET_SETTINGS_ERROR';

export const GENERAL_SETTINGS_REQUEST = 'GENERAL_SETTINGS_REQUEST';
export const GENERAL_SETTINGS_SUCCESS = 'GENERAL_SETTINGS_SUCCESS';
export const GENERAL_SETTINGS_ERROR = 'GENERAL_SETTINGS_ERROR';

export const GENERAL_SETTINGS_SAVE_REQUEST = 'GENERAL_SETTINGS_SAVE_REQUEST';
export const GENERAL_SETTINGS_SAVE_SUCCESS = 'GENERAL_SETTINGS_SAVE_SUCCESS';
export const GENERAL_SETTINGS_SAVE_ERROR = 'GENERAL_SETTINGS_SAVE_ERROR';

export const GETH_SETTINGS_SAVE_REQUEST = 'GETH_SETTINGS_SAVE_REQUEST';
export const GETH_SETTINGS_SAVE_SUCCESS = 'GETH_SETTINGS_SAVE_SUCCESS';
export const GETH_SETTINGS_SAVE_ERROR = 'GETH_SETTINGS_SAVE_ERROR';

export const IPFS_SETTINGS_SAVE_REQUEST = 'IPFS_SETTINGS_SAVE_REQUEST';
export const IPFS_SETTINGS_SAVE_SUCCESS = 'IPFS_SETTINGS_SAVE_SUCCESS';
export const IPFS_SETTINGS_SAVE_ERROR = 'IPFS_SETTINGS_SAVE_ERROR';

export const GET_USER_SETTINGS_SUCCESS = 'GET_USER_SETTINGS_SUCCESS';
export const GET_USER_SETTINGS_ERROR = 'GET_USER_SETTINGS_ERROR';

export const CLEAN_USER_SETTINGS = 'CLEAN_USER_SETTINGS';

export const START_FETCHING_SETTINGS = 'START_FETCHING_SETTINGS';
export const FINISH_FETCHING_SETTINGS = 'FINISH_FETCHING_SETTINGS';

export const SAVE_USER_SETTINGS = 'SAVE_USER_SETTINGS';
export const SAVE_USER_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_USER_SETTINGS_ERROR = 'SAVE_SETTINGS_ERROR';

export const SAVE_LATEST_MENTION_SUCCESS = 'SAVE_LATEST_MENTION_SUCCESS';
export const SAVE_LATEST_MENTION_ERROR = 'SAVE_LATEST_MENTION_ERROR';

export const SAVE_PASSWORD_PREFERENCE_SUCCESS = 'SAVE_PASSWORD_PREFERENCE_SUCCESS';
export const SAVE_PASSWORD_PREFERENCE_ERROR = 'SAVE_PASSWORD_PREFERENCE_ERROR';

// geth
// setup
export const SETUP_ADVANCED_SETTINGS = 'SETUP_ADVANCED_SETTINGS';
export const SETUP_GETH_DATADIR = 'SETUP_GETH_DATADIR';
export const SETUP_GETH_IPCPATH = 'SETUP_GETH_IPCPATH';
export const SETUP_GETH_CACHE_SIZE = 'SETUP_GETH_CACHE_SIZE';

// ipfs
    // setup
export const SETUP_IPFS_PATH = 'SETUP_IPFS_PATH';
export const SETUP_IPFS_API_PORT = 'SETUP_IPFS_API_PORT';
export const SETUP_IPFS_GATEWAY_PORT = 'SETUP_IPFS_GATEWAY_PORT';
    // start/stop

export const RETRY_SETUP = 'RETRY_SETUP';
export const RESET_SETTINGS = 'RESET_SETTINGS';

// general
export const CHANGE_THEME = 'CHANGE_THEME';

export const SAVE_CONFIGURATION = 'SAVE_CONFIGURATION';
