export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_SETTINGS_ERROR = 'SAVE_SETTINGS_ERROR';

export const GET_SETTINGS = 'GET_SETTINGS';
export const GET_SETTINGS_SUCCESS = 'GET_SETTINGS_SUCCESS';
export const GET_SETTINGS_ERROR = 'GET_SETTINGS_ERROR';

export const SAVE_USER_SETTINGS = 'SAVE_USER_SETTINGS';
export const SAVE_USER_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_USER_SETTINGS_ERROR = 'SAVE_SETTINGS_ERROR';

