
// geth
    // setup
export const SETUP_ADVANCED_SETTINGS = 'SETUP_ADVANCED_SETTINGS';
export const SETUP_GETH_DATADIR = 'SETUP_GETH_DATADIR';
export const SETUP_GETH_IPCPATH = 'SETUP_GETH_IPCPATH';
export const SETUP_GETH_CACHE_SIZE = 'SETUP_GETH_CACHE_SIZE';

// ipfs
    // setup
export const SETUP_IPFS_PATH = 'SETUP_IPFS_PATH';
export const SETUP_IPFS_API_PORT = 'SETUP_IPFS_API_PORT';
export const SETUP_IPFS_GATEWAY_PORT = 'SETUP_IPFS_GATEWAY_PORT';
    // start/stop

export const RETRY_SETUP = 'RETRY_SETUP';
