export const SYNC_ACTIVE = 'SYNC_ACTIVE';
export const SYNC_STOPPED = 'SYNC_STOPPED';
export const SYNC_FINISHED = 'SYNC_FINISHED';
export const SYNC_RESUME = 'SYNC_RESUME';
export const SYNC_ACTIVE_ERROR = 'SYNC_ACTIVE_ERROR';
export const SYNC_STOP_ERROR = 'SYNC_STOP_ERROR';
