export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_ERROR = 'GET_TAGS_ERROR';

export const CREATE_TAG = 'CREATE_TAG';
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
export const CREATE_TAG_ERROR = 'CREATE_TAG_ERROR';

export const CHECK_TAG_EXISTENCE = 'CHECK_TAG_EXISTENCE';
export const CHECK_TAG_EXISTENCE_SUCCESS = 'CHECK_TAG_EXISTENCE_SUCCESS';
export const CHECK_TAG_EXISTENCE_ERROR = 'CHECK_TAG_EXISTENCE_ERROR';
