export const GET_PENDING_TAGS = 'GET_PENDING_TAGS';
export const GET_PENDING_TAGS_SUCCESS = 'GET_PENDING_TAGS_SUCCESS';
export const GET_PENDING_TAGS_ERROR = 'GET_PENDING_TAGS_ERROR';

export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_ERROR = 'GET_TAGS_ERROR';

export const CREATE_TAG = 'CREATE_TAG';
export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS';
export const CREATE_TAG_ERROR = 'CREATE_TAG_ERROR';

export const SAVE_PENDING_TAG_SUCCESS = 'SAVE_PENDING_TAG_SUCCESS';
export const SAVE_PENDING_TAG_ERROR = 'SAVE_PENDING_TAG_ERROR';
