export const CREATE_TEMP_PROFILE = 'CREATE_TEMP_PROFILE';
export const CREATE_TEMP_PROFILE_SUCCESS = 'CREATE_TEMP_PROFILE_SUCCESS';
export const CREATE_TEMP_PROFILE_ERROR = 'CREATE_TEMP_PROFILE_ERROR';

export const UPDATE_TEMP_PROFILE = 'UPDATE_TEMP_PROFILE';
export const UPDATE_TEMP_PROFILE_SUCCESS = 'UPDATE_TEMP_PROFILE_SUCCESS';
export const UPDATE_TEMP_PROFILE_ERROR = 'UPDATE_TEMP_PROFILE_ERROR';

export const GET_TEMP_PROFILE_SUCCESS = 'GET_TEMP_PROFILE_SUCCESS';
export const GET_TEMP_PROFILE_ERROR = 'GET_TEMP_PROFILE_ERROR';

export const DELETE_TEMP_PROFILE_SUCCESS = 'DELETE_TEMP_PROFILE_SUCCESS';
export const DELETE_TEMP_PROFILE_ERROR = 'DELETE_TEMP_PROFILE_ERROR';

export const CREATE_ETH_ADDRESS = 'CREATE_ETH_ADDRESS';
export const CREATE_ETH_ADDRESS_SUCCESS = 'CREATE_ETH_ADDRESS_SUCCESS';
export const CREATE_ETH_ADDRESS_ERROR = 'CREATE_ETH_ADDRESS_ERROR';

export const REQUEST_FUND_FROM_FAUCET = 'REQUEST_FUND_FROM_FAUCET';
export const REQUEST_FUND_FROM_FAUCET_SUCCESS = 'REQUEST_FUND_FROM_FAUCET_SUCCESS';
export const REQUEST_FUND_FROM_FAUCET_ERROR = 'REQUEST_FUND_FROM_FAUCET_ERROR';

export const LISTEN_FAUCET_TX = 'LISTEN_FAUCET_TX';
export const LISTEN_PUBLISH_TX = 'LISTEN_PUBLISH_TX';

export const PUBLISH_PROFILE = 'PUBLISH_PROFILE';
export const PUBLISH_PROFILE_SUCCESS = 'PUBLISH_PROFILE_SUCCESS';
export const PUBLISH_PROFILE_ERROR = 'PUBLISH_PROFILE_ERROR';

export const CLEAR_TEMP_PROFILE_ERRORS = 'CLEAR_TEMP_PROFILE_ERRORS';
export const TEMP_LOGIN = 'TEMP_LOGIN';
