export const TRANSACTION_MINED_SUCCESS = 'TRANSACTION_MINED_SUCCESS';
export const TRANSACTION_MINED_ERROR = 'TRANSACTION_MINED_ERROR';

export const DELETE_PENDING_TX = 'DELETE_PENDING_TX';
export const DELETE_PENDING_TX_SUCCESS = 'DELETE_PENDING_TX_SUCCESS';
export const DELETE_PENDING_TX_ERROR = 'DELETE_PENDING_TX_ERROR';

export const ADD_TO_QUEUE_SUCCESS = 'ADD_TO_QUEUE_SUCCESS';
export const ADD_TO_QUEUE_ERROR = 'ADD_TO_QUEUE_ERROR';

export const GET_MINED_TRANSACTION = 'GET_MINED_TRANSACTION';
export const GET_MINED_TRANSACTION_ERROR = 'GET_MINED_TRANSACTION_ERROR';
export const GET_MINED_TRANSACTION_SUCCESS = 'GET_MINED_TRANSACTION_SUCCESS';

export const GET_PENDING_TRANSACTION = 'GET_PENDING_TRANSACTION';
export const GET_PENDING_TRANSACTION_ERROR = 'GET_PENDING_TRANSACTION_ERROR';
export const GET_PENDING_TRANSACTION_SUCCESS = 'GET_PENDING_TRANSACTION_SUCCESS';
