// flow-typed signature: 96491b2e9394d1a4cd480c8265d44bcf
// flow-typed version: <<STUB>>/@types/bluebird_v3.5.20/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/bluebird'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/bluebird' {
  declare module.exports: any;
}
