// flow-typed signature: 5816e84a2078ee657cf5eaf72fae80f6
// flow-typed version: <<STUB>>/@types/chai_v4.1.2/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chai' {
  declare module.exports: any;
}
