// flow-typed signature: d99054cb29ddc0322dbff9a10ad01017
// flow-typed version: <<STUB>>/@types/mocha_v2.2.48/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mocha' {
  declare module.exports: any;
}
