// flow-typed signature: cb28de261fc07f316c5433fb69f4d3ad
// flow-typed version: <<STUB>>/@types/node_v9.4.6/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
