// flow-typed signature: b519453fcec377f53fde445aabc0ef50
// flow-typed version: <<STUB>>/@types/rimraf_v2.0.2/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/rimraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/rimraf' {
  declare module.exports: any;
}
