// flow-typed signature: 9e83623b23359a6c45193eb3d28592e1
// flow-typed version: <<STUB>>/chai-immutable_v1.6.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-immutable/chai-immutable' {
  declare module.exports: any;
}

declare module 'chai-immutable/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-immutable/chai-immutable.js' {
  declare module.exports: $Exports<'chai-immutable/chai-immutable'>;
}
declare module 'chai-immutable/test/test.js' {
  declare module.exports: $Exports<'chai-immutable/test/test'>;
}
