// flow-typed signature: 4359f3a405d6028d4ddf0756ec70777a
// flow-typed version: <<STUB>>/co-mocha_v1.2.2/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'co-mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'co-mocha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'co-mocha/co-mocha' {
  declare module.exports: any;
}

declare module 'co-mocha/lib/co-mocha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'co-mocha/co-mocha.js' {
  declare module.exports: $Exports<'co-mocha/co-mocha'>;
}
declare module 'co-mocha/lib/co-mocha.js' {
  declare module.exports: $Exports<'co-mocha/lib/co-mocha'>;
}
