// flow-typed signature: 77338ba703143d197f7513c6f3ed0c3c
// flow-typed version: <<STUB>>/dexie_v2.0.2/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dexie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dexie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dexie/dist/dexie.es' {
  declare module.exports: any;
}

declare module 'dexie/dist/dexie' {
  declare module.exports: any;
}

declare module 'dexie/dist/dexie.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dexie/dist/dexie.es.js' {
  declare module.exports: $Exports<'dexie/dist/dexie.es'>;
}
declare module 'dexie/dist/dexie.js' {
  declare module.exports: $Exports<'dexie/dist/dexie'>;
}
declare module 'dexie/dist/dexie.min.js' {
  declare module.exports: $Exports<'dexie/dist/dexie.min'>;
}
