// flow-typed signature: adad88d18c6166f51611a3771fea8192
// flow-typed version: <<STUB>>/draft-js-anchor-plugin_v2.0.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-anchor-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-anchor-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-anchor-plugin/lib/components/Link/index' {
  declare module.exports: any;
}

declare module 'draft-js-anchor-plugin/lib/components/LinkButton/AddLinkForm' {
  declare module.exports: any;
}

declare module 'draft-js-anchor-plugin/lib/components/LinkButton/index' {
  declare module.exports: any;
}

declare module 'draft-js-anchor-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-anchor-plugin/lib/linkStrategy' {
  declare module.exports: any;
}

declare module 'draft-js-anchor-plugin/lib/utils/EditorUtils' {
  declare module.exports: any;
}

declare module 'draft-js-anchor-plugin/lib/utils/mailRegex' {
  declare module.exports: any;
}

declare module 'draft-js-anchor-plugin/lib/utils/urlRegex' {
  declare module.exports: any;
}

declare module 'draft-js-anchor-plugin/lib/utils/URLUtils' {
  declare module.exports: any;
}

declare module 'draft-js-anchor-plugin/postcss.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-anchor-plugin/lib/components/Link/index.js' {
  declare module.exports: $Exports<'draft-js-anchor-plugin/lib/components/Link/index'>;
}
declare module 'draft-js-anchor-plugin/lib/components/LinkButton/AddLinkForm.js' {
  declare module.exports: $Exports<'draft-js-anchor-plugin/lib/components/LinkButton/AddLinkForm'>;
}
declare module 'draft-js-anchor-plugin/lib/components/LinkButton/index.js' {
  declare module.exports: $Exports<'draft-js-anchor-plugin/lib/components/LinkButton/index'>;
}
declare module 'draft-js-anchor-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-anchor-plugin/lib/index'>;
}
declare module 'draft-js-anchor-plugin/lib/linkStrategy.js' {
  declare module.exports: $Exports<'draft-js-anchor-plugin/lib/linkStrategy'>;
}
declare module 'draft-js-anchor-plugin/lib/utils/EditorUtils.js' {
  declare module.exports: $Exports<'draft-js-anchor-plugin/lib/utils/EditorUtils'>;
}
declare module 'draft-js-anchor-plugin/lib/utils/mailRegex.js' {
  declare module.exports: $Exports<'draft-js-anchor-plugin/lib/utils/mailRegex'>;
}
declare module 'draft-js-anchor-plugin/lib/utils/urlRegex.js' {
  declare module.exports: $Exports<'draft-js-anchor-plugin/lib/utils/urlRegex'>;
}
declare module 'draft-js-anchor-plugin/lib/utils/URLUtils.js' {
  declare module.exports: $Exports<'draft-js-anchor-plugin/lib/utils/URLUtils'>;
}
declare module 'draft-js-anchor-plugin/postcss.config.js' {
  declare module.exports: $Exports<'draft-js-anchor-plugin/postcss.config'>;
}
