// flow-typed signature: 2216c2e121d54a61d410227efaf1237c
// flow-typed version: <<STUB>>/draft-js-emoji-plugin_v2.0.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-emoji-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-emoji-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-emoji-plugin/lib/components/Emoji/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Entry/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Groups/Group/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Groups/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Nav/Entry/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Nav/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/ToneSelect/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/components/EmojiSuggestions/Entry/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/components/EmojiSuggestions/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/components/EmojiSuggestionsPortal/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/constants/defaultEmojiGroups' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/emojiStrategy' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/emojiSuggestionsStrategy' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/modifiers/addEmoji' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/modifiers/attachImmutableEntitiesToEmojis' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/convertShortNameToUnicode' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/createEmojisFromStrategy' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/decodeOffsetKey' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/emojiList' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/getSearchText' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/getWordAt' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/mappedUnicode' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/lib/utils/positionSuggestions' {
  declare module.exports: any;
}

declare module 'draft-js-emoji-plugin/postcss.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-emoji-plugin/lib/components/Emoji/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/Emoji/index'>;
}
declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/EmojiSelect/index'>;
}
declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Entry/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Entry/index'>;
}
declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Groups/Group/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Groups/Group/index'>;
}
declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Groups/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Groups/index'>;
}
declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/index'>;
}
declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Nav/Entry/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Nav/Entry/index'>;
}
declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Nav/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/Nav/index'>;
}
declare module 'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/ToneSelect/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/EmojiSelect/Popover/ToneSelect/index'>;
}
declare module 'draft-js-emoji-plugin/lib/components/EmojiSuggestions/Entry/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/EmojiSuggestions/Entry/index'>;
}
declare module 'draft-js-emoji-plugin/lib/components/EmojiSuggestions/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/EmojiSuggestions/index'>;
}
declare module 'draft-js-emoji-plugin/lib/components/EmojiSuggestionsPortal/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/components/EmojiSuggestionsPortal/index'>;
}
declare module 'draft-js-emoji-plugin/lib/constants/defaultEmojiGroups.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/constants/defaultEmojiGroups'>;
}
declare module 'draft-js-emoji-plugin/lib/emojiStrategy.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/emojiStrategy'>;
}
declare module 'draft-js-emoji-plugin/lib/emojiSuggestionsStrategy.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/emojiSuggestionsStrategy'>;
}
declare module 'draft-js-emoji-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/index'>;
}
declare module 'draft-js-emoji-plugin/lib/modifiers/addEmoji.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/modifiers/addEmoji'>;
}
declare module 'draft-js-emoji-plugin/lib/modifiers/attachImmutableEntitiesToEmojis.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/modifiers/attachImmutableEntitiesToEmojis'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/convertShortNameToUnicode.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/convertShortNameToUnicode'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/createEmojisFromStrategy.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/createEmojisFromStrategy'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/decodeOffsetKey.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/decodeOffsetKey'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/emojiList.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/emojiList'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/getSearchText.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/getSearchText'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/getWordAt.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/getWordAt'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/mappedUnicode.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/mappedUnicode'>;
}
declare module 'draft-js-emoji-plugin/lib/utils/positionSuggestions.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/lib/utils/positionSuggestions'>;
}
declare module 'draft-js-emoji-plugin/postcss.config.js' {
  declare module.exports: $Exports<'draft-js-emoji-plugin/postcss.config'>;
}
