// flow-typed signature: cabf0fe84f9dd826258e0f9c49423058
// flow-typed version: <<STUB>>/ethereumjs-testrpc_v6.0.3/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ethereumjs-testrpc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ethereumjs-testrpc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ethereumjs-testrpc/build/cli.node' {
  declare module.exports: any;
}

declare module 'ethereumjs-testrpc/build/lib.node' {
  declare module.exports: any;
}

declare module 'ethereumjs-testrpc/build/provider.node' {
  declare module.exports: any;
}

declare module 'ethereumjs-testrpc/build/server.node' {
  declare module.exports: any;
}

declare module 'ethereumjs-testrpc/cli' {
  declare module.exports: any;
}

declare module 'ethereumjs-testrpc/lib' {
  declare module.exports: any;
}

declare module 'ethereumjs-testrpc/nil' {
  declare module.exports: any;
}

declare module 'ethereumjs-testrpc/perf/transactions' {
  declare module.exports: any;
}

declare module 'ethereumjs-testrpc/webpack/cli.webpack.config' {
  declare module.exports: any;
}

declare module 'ethereumjs-testrpc/webpack/lib.webpack.config' {
  declare module.exports: any;
}

declare module 'ethereumjs-testrpc/webpack/provider.webpack.config' {
  declare module.exports: any;
}

declare module 'ethereumjs-testrpc/webpack/server.webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ethereumjs-testrpc/build/cli.node.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/build/cli.node'>;
}
declare module 'ethereumjs-testrpc/build/lib.node.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/build/lib.node'>;
}
declare module 'ethereumjs-testrpc/build/provider.node.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/build/provider.node'>;
}
declare module 'ethereumjs-testrpc/build/server.node.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/build/server.node'>;
}
declare module 'ethereumjs-testrpc/cli.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/cli'>;
}
declare module 'ethereumjs-testrpc/lib.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/lib'>;
}
declare module 'ethereumjs-testrpc/nil.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/nil'>;
}
declare module 'ethereumjs-testrpc/perf/transactions.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/perf/transactions'>;
}
declare module 'ethereumjs-testrpc/webpack/cli.webpack.config.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/webpack/cli.webpack.config'>;
}
declare module 'ethereumjs-testrpc/webpack/lib.webpack.config.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/webpack/lib.webpack.config'>;
}
declare module 'ethereumjs-testrpc/webpack/provider.webpack.config.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/webpack/provider.webpack.config'>;
}
declare module 'ethereumjs-testrpc/webpack/server.webpack.config.js' {
  declare module.exports: $Exports<'ethereumjs-testrpc/webpack/server.webpack.config'>;
}
