// flow-typed signature: 4a6a5f7a294d4b6130cb7d4512476672
// flow-typed version: <<STUB>>/idna-uts46_v1.1.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'idna-uts46'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'idna-uts46' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'idna-uts46/idna-map' {
  declare module.exports: any;
}

declare module 'idna-uts46/test/node_fs_shim' {
  declare module.exports: any;
}

declare module 'idna-uts46/test/test-idna-vector' {
  declare module.exports: any;
}

declare module 'idna-uts46/test/test-uts46' {
  declare module.exports: any;
}

declare module 'idna-uts46/uts46' {
  declare module.exports: any;
}

// Filename aliases
declare module 'idna-uts46/idna-map.js' {
  declare module.exports: $Exports<'idna-uts46/idna-map'>;
}
declare module 'idna-uts46/test/node_fs_shim.js' {
  declare module.exports: $Exports<'idna-uts46/test/node_fs_shim'>;
}
declare module 'idna-uts46/test/test-idna-vector.js' {
  declare module.exports: $Exports<'idna-uts46/test/test-idna-vector'>;
}
declare module 'idna-uts46/test/test-uts46.js' {
  declare module.exports: $Exports<'idna-uts46/test/test-uts46'>;
}
declare module 'idna-uts46/uts46.js' {
  declare module.exports: $Exports<'idna-uts46/uts46'>;
}
