// flow-typed signature: 54a213840a0de134e9159dc547422f90
// flow-typed version: <<STUB>>/joi-validation-strategy_v0.3.3/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'joi-validation-strategy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'joi-validation-strategy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'joi-validation-strategy/lib/joiValidationStrategy' {
  declare module.exports: any;
}

declare module 'joi-validation-strategy/lib/utils/collectErrors' {
  declare module.exports: any;
}

declare module 'joi-validation-strategy/lib/utils/decodeMessages' {
  declare module.exports: any;
}

declare module 'joi-validation-strategy/lib/utils/hydrate' {
  declare module.exports: any;
}

declare module 'joi-validation-strategy/lib/utils/index' {
  declare module.exports: any;
}

declare module 'joi-validation-strategy/lib/utils/pickMessages' {
  declare module.exports: any;
}

// Filename aliases
declare module 'joi-validation-strategy/lib/joiValidationStrategy.js' {
  declare module.exports: $Exports<'joi-validation-strategy/lib/joiValidationStrategy'>;
}
declare module 'joi-validation-strategy/lib/utils/collectErrors.js' {
  declare module.exports: $Exports<'joi-validation-strategy/lib/utils/collectErrors'>;
}
declare module 'joi-validation-strategy/lib/utils/decodeMessages.js' {
  declare module.exports: $Exports<'joi-validation-strategy/lib/utils/decodeMessages'>;
}
declare module 'joi-validation-strategy/lib/utils/hydrate.js' {
  declare module.exports: $Exports<'joi-validation-strategy/lib/utils/hydrate'>;
}
declare module 'joi-validation-strategy/lib/utils/index.js' {
  declare module.exports: $Exports<'joi-validation-strategy/lib/utils/index'>;
}
declare module 'joi-validation-strategy/lib/utils/pickMessages.js' {
  declare module.exports: $Exports<'joi-validation-strategy/lib/utils/pickMessages'>;
}
