// flow-typed signature: 2d8ce4c82ab5bc1823bb3eae20893d6b
// flow-typed version: <<STUB>>/lodash.throttle_v4.1.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.throttle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.throttle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.throttle/index' {
  declare module.exports: $Exports<'lodash.throttle'>;
}
declare module 'lodash.throttle/index.js' {
  declare module.exports: $Exports<'lodash.throttle'>;
}
