// flow-typed signature: 4d8009ced70f3c25220e27206ebb5e98
// flow-typed version: <<STUB>>/megadraft_v0.4.35/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'megadraft'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'megadraft' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'megadraft/lib/actions/default' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/Dropdown' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/DropdownItem' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/Link' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/LinkInput' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/Media' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/MediaMessage' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/MediaWrapper' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/MegadraftEditor' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/ModalPluginItem' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/ModalPluginList' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/plugin' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/plugin/BlockAction' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/plugin/BlockActionGroup' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/plugin/BlockContent' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/plugin/BlockControls' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/plugin/BlockData' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/plugin/BlockInput' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/plugin/BlockWrapper' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/plugin/CommonBlock' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/plugin/defaults' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/PluginsModal' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/Separator' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/Sidebar' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/Toolbar' {
  declare module.exports: any;
}

declare module 'megadraft/lib/components/ToolbarItem' {
  declare module.exports: any;
}

declare module 'megadraft/lib/decorator' {
  declare module.exports: any;
}

declare module 'megadraft/lib/decorators/defaultDecorator' {
  declare module.exports: any;
}

declare module 'megadraft/lib/entity_inputs/default' {
  declare module.exports: any;
}

declare module 'megadraft/lib/entity_inputs/LinkInput' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/blockquote' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/bold' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/close' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/crop' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/cross' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/delete' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/dropdownArrow' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/edit' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/ellipsis' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/error' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/h2' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/image' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/italic' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/link' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/mediaBig' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/mediaMedium' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/mediaSmall' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/more' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/ol' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/ul' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/unlink' {
  declare module.exports: any;
}

declare module 'megadraft/lib/icons/video' {
  declare module.exports: any;
}

declare module 'megadraft/lib/insertDataBlock' {
  declare module.exports: any;
}

declare module 'megadraft/lib/Megadraft' {
  declare module.exports: any;
}

declare module 'megadraft/lib/plugins/default' {
  declare module.exports: any;
}

declare module 'megadraft/lib/plugins/image/ImageBlock' {
  declare module.exports: any;
}

declare module 'megadraft/lib/plugins/image/ImageBlockStyle' {
  declare module.exports: any;
}

declare module 'megadraft/lib/plugins/image/ImageButton' {
  declare module.exports: any;
}

declare module 'megadraft/lib/plugins/image/plugin' {
  declare module.exports: any;
}

declare module 'megadraft/lib/plugins/not-found/NotFoundBlock' {
  declare module.exports: any;
}

declare module 'megadraft/lib/plugins/not-found/plugin' {
  declare module.exports: any;
}

declare module 'megadraft/lib/plugins/video/plugin' {
  declare module.exports: any;
}

declare module 'megadraft/lib/plugins/video/VideoBlock' {
  declare module.exports: any;
}

declare module 'megadraft/lib/plugins/video/VideoBlockStyle' {
  declare module.exports: any;
}

declare module 'megadraft/lib/plugins/video/VideoButton' {
  declare module.exports: any;
}

declare module 'megadraft/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'megadraft/lib/actions/default.js' {
  declare module.exports: $Exports<'megadraft/lib/actions/default'>;
}
declare module 'megadraft/lib/components/Dropdown.js' {
  declare module.exports: $Exports<'megadraft/lib/components/Dropdown'>;
}
declare module 'megadraft/lib/components/DropdownItem.js' {
  declare module.exports: $Exports<'megadraft/lib/components/DropdownItem'>;
}
declare module 'megadraft/lib/components/Link.js' {
  declare module.exports: $Exports<'megadraft/lib/components/Link'>;
}
declare module 'megadraft/lib/components/LinkInput.js' {
  declare module.exports: $Exports<'megadraft/lib/components/LinkInput'>;
}
declare module 'megadraft/lib/components/Media.js' {
  declare module.exports: $Exports<'megadraft/lib/components/Media'>;
}
declare module 'megadraft/lib/components/MediaMessage.js' {
  declare module.exports: $Exports<'megadraft/lib/components/MediaMessage'>;
}
declare module 'megadraft/lib/components/MediaWrapper.js' {
  declare module.exports: $Exports<'megadraft/lib/components/MediaWrapper'>;
}
declare module 'megadraft/lib/components/MegadraftEditor.js' {
  declare module.exports: $Exports<'megadraft/lib/components/MegadraftEditor'>;
}
declare module 'megadraft/lib/components/ModalPluginItem.js' {
  declare module.exports: $Exports<'megadraft/lib/components/ModalPluginItem'>;
}
declare module 'megadraft/lib/components/ModalPluginList.js' {
  declare module.exports: $Exports<'megadraft/lib/components/ModalPluginList'>;
}
declare module 'megadraft/lib/components/plugin.js' {
  declare module.exports: $Exports<'megadraft/lib/components/plugin'>;
}
declare module 'megadraft/lib/components/plugin/BlockAction.js' {
  declare module.exports: $Exports<'megadraft/lib/components/plugin/BlockAction'>;
}
declare module 'megadraft/lib/components/plugin/BlockActionGroup.js' {
  declare module.exports: $Exports<'megadraft/lib/components/plugin/BlockActionGroup'>;
}
declare module 'megadraft/lib/components/plugin/BlockContent.js' {
  declare module.exports: $Exports<'megadraft/lib/components/plugin/BlockContent'>;
}
declare module 'megadraft/lib/components/plugin/BlockControls.js' {
  declare module.exports: $Exports<'megadraft/lib/components/plugin/BlockControls'>;
}
declare module 'megadraft/lib/components/plugin/BlockData.js' {
  declare module.exports: $Exports<'megadraft/lib/components/plugin/BlockData'>;
}
declare module 'megadraft/lib/components/plugin/BlockInput.js' {
  declare module.exports: $Exports<'megadraft/lib/components/plugin/BlockInput'>;
}
declare module 'megadraft/lib/components/plugin/BlockWrapper.js' {
  declare module.exports: $Exports<'megadraft/lib/components/plugin/BlockWrapper'>;
}
declare module 'megadraft/lib/components/plugin/CommonBlock.js' {
  declare module.exports: $Exports<'megadraft/lib/components/plugin/CommonBlock'>;
}
declare module 'megadraft/lib/components/plugin/defaults.js' {
  declare module.exports: $Exports<'megadraft/lib/components/plugin/defaults'>;
}
declare module 'megadraft/lib/components/PluginsModal.js' {
  declare module.exports: $Exports<'megadraft/lib/components/PluginsModal'>;
}
declare module 'megadraft/lib/components/Separator.js' {
  declare module.exports: $Exports<'megadraft/lib/components/Separator'>;
}
declare module 'megadraft/lib/components/Sidebar.js' {
  declare module.exports: $Exports<'megadraft/lib/components/Sidebar'>;
}
declare module 'megadraft/lib/components/Toolbar.js' {
  declare module.exports: $Exports<'megadraft/lib/components/Toolbar'>;
}
declare module 'megadraft/lib/components/ToolbarItem.js' {
  declare module.exports: $Exports<'megadraft/lib/components/ToolbarItem'>;
}
declare module 'megadraft/lib/decorator.js' {
  declare module.exports: $Exports<'megadraft/lib/decorator'>;
}
declare module 'megadraft/lib/decorators/defaultDecorator.js' {
  declare module.exports: $Exports<'megadraft/lib/decorators/defaultDecorator'>;
}
declare module 'megadraft/lib/entity_inputs/default.js' {
  declare module.exports: $Exports<'megadraft/lib/entity_inputs/default'>;
}
declare module 'megadraft/lib/entity_inputs/LinkInput.js' {
  declare module.exports: $Exports<'megadraft/lib/entity_inputs/LinkInput'>;
}
declare module 'megadraft/lib/icons.js' {
  declare module.exports: $Exports<'megadraft/lib/icons'>;
}
declare module 'megadraft/lib/icons/blockquote.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/blockquote'>;
}
declare module 'megadraft/lib/icons/bold.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/bold'>;
}
declare module 'megadraft/lib/icons/close.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/close'>;
}
declare module 'megadraft/lib/icons/crop.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/crop'>;
}
declare module 'megadraft/lib/icons/cross.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/cross'>;
}
declare module 'megadraft/lib/icons/delete.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/delete'>;
}
declare module 'megadraft/lib/icons/dropdownArrow.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/dropdownArrow'>;
}
declare module 'megadraft/lib/icons/edit.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/edit'>;
}
declare module 'megadraft/lib/icons/ellipsis.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/ellipsis'>;
}
declare module 'megadraft/lib/icons/error.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/error'>;
}
declare module 'megadraft/lib/icons/h2.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/h2'>;
}
declare module 'megadraft/lib/icons/image.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/image'>;
}
declare module 'megadraft/lib/icons/italic.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/italic'>;
}
declare module 'megadraft/lib/icons/link.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/link'>;
}
declare module 'megadraft/lib/icons/mediaBig.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/mediaBig'>;
}
declare module 'megadraft/lib/icons/mediaMedium.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/mediaMedium'>;
}
declare module 'megadraft/lib/icons/mediaSmall.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/mediaSmall'>;
}
declare module 'megadraft/lib/icons/more.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/more'>;
}
declare module 'megadraft/lib/icons/ol.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/ol'>;
}
declare module 'megadraft/lib/icons/ul.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/ul'>;
}
declare module 'megadraft/lib/icons/unlink.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/unlink'>;
}
declare module 'megadraft/lib/icons/video.js' {
  declare module.exports: $Exports<'megadraft/lib/icons/video'>;
}
declare module 'megadraft/lib/insertDataBlock.js' {
  declare module.exports: $Exports<'megadraft/lib/insertDataBlock'>;
}
declare module 'megadraft/lib/Megadraft.js' {
  declare module.exports: $Exports<'megadraft/lib/Megadraft'>;
}
declare module 'megadraft/lib/plugins/default.js' {
  declare module.exports: $Exports<'megadraft/lib/plugins/default'>;
}
declare module 'megadraft/lib/plugins/image/ImageBlock.js' {
  declare module.exports: $Exports<'megadraft/lib/plugins/image/ImageBlock'>;
}
declare module 'megadraft/lib/plugins/image/ImageBlockStyle.js' {
  declare module.exports: $Exports<'megadraft/lib/plugins/image/ImageBlockStyle'>;
}
declare module 'megadraft/lib/plugins/image/ImageButton.js' {
  declare module.exports: $Exports<'megadraft/lib/plugins/image/ImageButton'>;
}
declare module 'megadraft/lib/plugins/image/plugin.js' {
  declare module.exports: $Exports<'megadraft/lib/plugins/image/plugin'>;
}
declare module 'megadraft/lib/plugins/not-found/NotFoundBlock.js' {
  declare module.exports: $Exports<'megadraft/lib/plugins/not-found/NotFoundBlock'>;
}
declare module 'megadraft/lib/plugins/not-found/plugin.js' {
  declare module.exports: $Exports<'megadraft/lib/plugins/not-found/plugin'>;
}
declare module 'megadraft/lib/plugins/video/plugin.js' {
  declare module.exports: $Exports<'megadraft/lib/plugins/video/plugin'>;
}
declare module 'megadraft/lib/plugins/video/VideoBlock.js' {
  declare module.exports: $Exports<'megadraft/lib/plugins/video/VideoBlock'>;
}
declare module 'megadraft/lib/plugins/video/VideoBlockStyle.js' {
  declare module.exports: $Exports<'megadraft/lib/plugins/video/VideoBlockStyle'>;
}
declare module 'megadraft/lib/plugins/video/VideoButton.js' {
  declare module.exports: $Exports<'megadraft/lib/plugins/video/VideoButton'>;
}
declare module 'megadraft/lib/utils.js' {
  declare module.exports: $Exports<'megadraft/lib/utils'>;
}
