// flow-typed signature: 651e07c992d01cb92a4a07e82cd96227
// flow-typed version: <<STUB>>/mock-css-modules_v1.0.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-css-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-css-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mock-css-modules/index' {
  declare module.exports: $Exports<'mock-css-modules'>;
}
declare module 'mock-css-modules/index.js' {
  declare module.exports: $Exports<'mock-css-modules'>;
}
