// flow-typed signature: 22f33cd3f414ac400b7a75fc29447f3b
// flow-typed version: <<STUB>>/node-pre-gyp_v0.6.39/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-pre-gyp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-pre-gyp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-pre-gyp/lib/build' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/clean' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/configure' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/info' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/install' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/node-pre-gyp' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/package' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/pre-binding' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/publish' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/rebuild' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/reinstall' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/reveal' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/testbinary' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/testpackage' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/unpublish' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/util/compile' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/util/handle_gyp_opts' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/util/s3_setup' {
  declare module.exports: any;
}

declare module 'node-pre-gyp/lib/util/versioning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-pre-gyp/lib/build.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/build'>;
}
declare module 'node-pre-gyp/lib/clean.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/clean'>;
}
declare module 'node-pre-gyp/lib/configure.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/configure'>;
}
declare module 'node-pre-gyp/lib/info.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/info'>;
}
declare module 'node-pre-gyp/lib/install.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/install'>;
}
declare module 'node-pre-gyp/lib/node-pre-gyp.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/node-pre-gyp'>;
}
declare module 'node-pre-gyp/lib/package.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/package'>;
}
declare module 'node-pre-gyp/lib/pre-binding.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/pre-binding'>;
}
declare module 'node-pre-gyp/lib/publish.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/publish'>;
}
declare module 'node-pre-gyp/lib/rebuild.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/rebuild'>;
}
declare module 'node-pre-gyp/lib/reinstall.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/reinstall'>;
}
declare module 'node-pre-gyp/lib/reveal.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/reveal'>;
}
declare module 'node-pre-gyp/lib/testbinary.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/testbinary'>;
}
declare module 'node-pre-gyp/lib/testpackage.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/testpackage'>;
}
declare module 'node-pre-gyp/lib/unpublish.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/unpublish'>;
}
declare module 'node-pre-gyp/lib/util/compile.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/util/compile'>;
}
declare module 'node-pre-gyp/lib/util/handle_gyp_opts.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/util/handle_gyp_opts'>;
}
declare module 'node-pre-gyp/lib/util/s3_setup.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/util/s3_setup'>;
}
declare module 'node-pre-gyp/lib/util/versioning.js' {
  declare module.exports: $Exports<'node-pre-gyp/lib/util/versioning'>;
}
