// flow-typed signature: 760d7416436e6000b2c6f8e4e5c8e780
// flow-typed version: <<STUB>>/pica_v4.0.2/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pica'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pica' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pica/dist/pica' {
  declare module.exports: any;
}

declare module 'pica/dist/pica.min' {
  declare module.exports: any;
}

declare module 'pica/lib/mathlib' {
  declare module.exports: any;
}

declare module 'pica/lib/mm_resize/convolve_wasm_base64' {
  declare module.exports: any;
}

declare module 'pica/lib/mm_resize/convolve' {
  declare module.exports: any;
}

declare module 'pica/lib/mm_resize/index' {
  declare module.exports: any;
}

declare module 'pica/lib/mm_resize/resize_filter_gen' {
  declare module.exports: any;
}

declare module 'pica/lib/mm_resize/resize_filter_info' {
  declare module.exports: any;
}

declare module 'pica/lib/mm_resize/resize_wasm' {
  declare module.exports: any;
}

declare module 'pica/lib/mm_resize/resize' {
  declare module.exports: any;
}

declare module 'pica/lib/pool' {
  declare module.exports: any;
}

declare module 'pica/lib/tiler' {
  declare module.exports: any;
}

declare module 'pica/lib/utils' {
  declare module.exports: any;
}

declare module 'pica/lib/worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pica/dist/pica.js' {
  declare module.exports: $Exports<'pica/dist/pica'>;
}
declare module 'pica/dist/pica.min.js' {
  declare module.exports: $Exports<'pica/dist/pica.min'>;
}
declare module 'pica/index' {
  declare module.exports: $Exports<'pica'>;
}
declare module 'pica/index.js' {
  declare module.exports: $Exports<'pica'>;
}
declare module 'pica/lib/mathlib.js' {
  declare module.exports: $Exports<'pica/lib/mathlib'>;
}
declare module 'pica/lib/mm_resize/convolve_wasm_base64.js' {
  declare module.exports: $Exports<'pica/lib/mm_resize/convolve_wasm_base64'>;
}
declare module 'pica/lib/mm_resize/convolve.js' {
  declare module.exports: $Exports<'pica/lib/mm_resize/convolve'>;
}
declare module 'pica/lib/mm_resize/index.js' {
  declare module.exports: $Exports<'pica/lib/mm_resize/index'>;
}
declare module 'pica/lib/mm_resize/resize_filter_gen.js' {
  declare module.exports: $Exports<'pica/lib/mm_resize/resize_filter_gen'>;
}
declare module 'pica/lib/mm_resize/resize_filter_info.js' {
  declare module.exports: $Exports<'pica/lib/mm_resize/resize_filter_info'>;
}
declare module 'pica/lib/mm_resize/resize_wasm.js' {
  declare module.exports: $Exports<'pica/lib/mm_resize/resize_wasm'>;
}
declare module 'pica/lib/mm_resize/resize.js' {
  declare module.exports: $Exports<'pica/lib/mm_resize/resize'>;
}
declare module 'pica/lib/pool.js' {
  declare module.exports: $Exports<'pica/lib/pool'>;
}
declare module 'pica/lib/tiler.js' {
  declare module.exports: $Exports<'pica/lib/tiler'>;
}
declare module 'pica/lib/utils.js' {
  declare module.exports: $Exports<'pica/lib/utils'>;
}
declare module 'pica/lib/worker.js' {
  declare module.exports: $Exports<'pica/lib/worker'>;
}
