// flow-typed signature: 246f8f27f137ba17c3165be1b1f91319
// flow-typed version: <<STUB>>/postcss-modules-scope_v1.1.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-modules-scope'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-modules-scope' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-modules-scope/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-modules-scope/lib/index.js' {
  declare module.exports: $Exports<'postcss-modules-scope/lib/index'>;
}
