// flow-typed signature: 39a9e87de5a59948848ad5eee2612f04
// flow-typed version: <<STUB>>/postcss-modules-values_v1.3.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-modules-values'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-modules-values' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-modules-values/lib/index' {
  declare module.exports: any;
}

declare module 'postcss-modules-values/src/index' {
  declare module.exports: any;
}

declare module 'postcss-modules-values/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-modules-values/lib/index.js' {
  declare module.exports: $Exports<'postcss-modules-values/lib/index'>;
}
declare module 'postcss-modules-values/src/index.js' {
  declare module.exports: $Exports<'postcss-modules-values/src/index'>;
}
declare module 'postcss-modules-values/test/index.js' {
  declare module.exports: $Exports<'postcss-modules-values/test/index'>;
}
