// flow-typed signature: 441753709de7c2a044c346e28d20521f
// flow-typed version: <<STUB>>/postcss-modules-local-by-default_v1.2.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-modules-local-by-default'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-modules-local-by-default' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-modules-local-by-default/index' {
  declare module.exports: $Exports<'postcss-modules-local-by-default'>;
}
declare module 'postcss-modules-local-by-default/index.js' {
  declare module.exports: $Exports<'postcss-modules-local-by-default'>;
}
