// flow-typed signature: 95af7c250fbf63ca5e6099d335e9b333
// flow-typed version: <<STUB>>/qrcode.react_v0.8.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qrcode.react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qrcode.react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qrcode.react/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qrcode.react/lib/index.js' {
  declare module.exports: $Exports<'qrcode.react/lib/index'>;
}
