// flow-typed signature: 255d47be9b714990de0476a80d4e5ef7
// flow-typed version: <<STUB>>/react-validation-mixin_v5.4.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-validation-mixin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-validation-mixin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-validation-mixin/lib/components/validationMixin' {
  declare module.exports: any;
}

declare module 'react-validation-mixin/lib/index' {
  declare module.exports: any;
}

declare module 'react-validation-mixin/lib/spec/components/MixinSpec' {
  declare module.exports: any;
}

declare module 'react-validation-mixin/lib/spec/components/Signup' {
  declare module.exports: any;
}

declare module 'react-validation-mixin/lib/spec/utils/isSomeSpec' {
  declare module.exports: any;
}

declare module 'react-validation-mixin/lib/spec/ValidationFactorySpec' {
  declare module.exports: any;
}

declare module 'react-validation-mixin/lib/utils/defined' {
  declare module.exports: any;
}

declare module 'react-validation-mixin/lib/utils/flattenErrorsObject' {
  declare module.exports: any;
}

declare module 'react-validation-mixin/lib/utils/index' {
  declare module.exports: any;
}

declare module 'react-validation-mixin/lib/utils/isSome' {
  declare module.exports: any;
}

declare module 'react-validation-mixin/lib/validationFactory' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-validation-mixin/lib/components/validationMixin.js' {
  declare module.exports: $Exports<'react-validation-mixin/lib/components/validationMixin'>;
}
declare module 'react-validation-mixin/lib/index.js' {
  declare module.exports: $Exports<'react-validation-mixin/lib/index'>;
}
declare module 'react-validation-mixin/lib/spec/components/MixinSpec.js' {
  declare module.exports: $Exports<'react-validation-mixin/lib/spec/components/MixinSpec'>;
}
declare module 'react-validation-mixin/lib/spec/components/Signup.js' {
  declare module.exports: $Exports<'react-validation-mixin/lib/spec/components/Signup'>;
}
declare module 'react-validation-mixin/lib/spec/utils/isSomeSpec.js' {
  declare module.exports: $Exports<'react-validation-mixin/lib/spec/utils/isSomeSpec'>;
}
declare module 'react-validation-mixin/lib/spec/ValidationFactorySpec.js' {
  declare module.exports: $Exports<'react-validation-mixin/lib/spec/ValidationFactorySpec'>;
}
declare module 'react-validation-mixin/lib/utils/defined.js' {
  declare module.exports: $Exports<'react-validation-mixin/lib/utils/defined'>;
}
declare module 'react-validation-mixin/lib/utils/flattenErrorsObject.js' {
  declare module.exports: $Exports<'react-validation-mixin/lib/utils/flattenErrorsObject'>;
}
declare module 'react-validation-mixin/lib/utils/index.js' {
  declare module.exports: $Exports<'react-validation-mixin/lib/utils/index'>;
}
declare module 'react-validation-mixin/lib/utils/isSome.js' {
  declare module.exports: $Exports<'react-validation-mixin/lib/utils/isSome'>;
}
declare module 'react-validation-mixin/lib/validationFactory.js' {
  declare module.exports: $Exports<'react-validation-mixin/lib/validationFactory'>;
}
