// flow-typed signature: 5c7ffa72c5e49815ed201a219b4a6dc6
// flow-typed version: <<STUB>>/react-intl-translations-manager_v5.0.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl-translations-manager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl-translations-manager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intl-translations-manager/dist/compareByKey' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/dist/core' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/dist/createSingleMessagesFile' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/dist/getDefaultMessages' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/dist/getLanguageReport' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/dist/index' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/dist/manageTranslations' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/dist/printer' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/dist/printResults' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/dist/readFile' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/dist/readMessageFiles' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/dist/stringify' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/compareByKey' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/core' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/createSingleMessagesFile' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/getDefaultMessages' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/getLanguageReport' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/index' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/manageTranslations' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/printer' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/printResults' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/readFile' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/readMessageFiles' {
  declare module.exports: any;
}

declare module 'react-intl-translations-manager/src/stringify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intl-translations-manager/dist/compareByKey.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/compareByKey'>;
}
declare module 'react-intl-translations-manager/dist/core.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/core'>;
}
declare module 'react-intl-translations-manager/dist/createSingleMessagesFile.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/createSingleMessagesFile'>;
}
declare module 'react-intl-translations-manager/dist/getDefaultMessages.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/getDefaultMessages'>;
}
declare module 'react-intl-translations-manager/dist/getLanguageReport.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/getLanguageReport'>;
}
declare module 'react-intl-translations-manager/dist/index.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/index'>;
}
declare module 'react-intl-translations-manager/dist/manageTranslations.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/manageTranslations'>;
}
declare module 'react-intl-translations-manager/dist/printer.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/printer'>;
}
declare module 'react-intl-translations-manager/dist/printResults.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/printResults'>;
}
declare module 'react-intl-translations-manager/dist/readFile.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/readFile'>;
}
declare module 'react-intl-translations-manager/dist/readMessageFiles.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/readMessageFiles'>;
}
declare module 'react-intl-translations-manager/dist/stringify.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/dist/stringify'>;
}
declare module 'react-intl-translations-manager/src/compareByKey.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/compareByKey'>;
}
declare module 'react-intl-translations-manager/src/core.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/core'>;
}
declare module 'react-intl-translations-manager/src/createSingleMessagesFile.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/createSingleMessagesFile'>;
}
declare module 'react-intl-translations-manager/src/getDefaultMessages.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/getDefaultMessages'>;
}
declare module 'react-intl-translations-manager/src/getLanguageReport.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/getLanguageReport'>;
}
declare module 'react-intl-translations-manager/src/index.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/index'>;
}
declare module 'react-intl-translations-manager/src/manageTranslations.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/manageTranslations'>;
}
declare module 'react-intl-translations-manager/src/printer.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/printer'>;
}
declare module 'react-intl-translations-manager/src/printResults.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/printResults'>;
}
declare module 'react-intl-translations-manager/src/readFile.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/readFile'>;
}
declare module 'react-intl-translations-manager/src/readMessageFiles.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/readMessageFiles'>;
}
declare module 'react-intl-translations-manager/src/stringify.js' {
  declare module.exports: $Exports<'react-intl-translations-manager/src/stringify'>;
}
