// flow-typed signature: 255ec9447de6976c61f82da0704bbfdf
// flow-typed version: <<STUB>>/redux-saga-tester_v1.0.379/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga-tester'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga-tester' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga-tester/dist/SagaTester' {
  declare module.exports: any;
}

declare module 'redux-saga-tester/src/SagaTester' {
  declare module.exports: any;
}

declare module 'redux-saga-tester/test/SagaTester.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga-tester/dist/SagaTester.js' {
  declare module.exports: $Exports<'redux-saga-tester/dist/SagaTester'>;
}
declare module 'redux-saga-tester/src/SagaTester.js' {
  declare module.exports: $Exports<'redux-saga-tester/src/SagaTester'>;
}
declare module 'redux-saga-tester/test/SagaTester.spec.js' {
  declare module.exports: $Exports<'redux-saga-tester/test/SagaTester.spec'>;
}
