// flow-typed signature: be2efd615ef9442a2ddd2f44cb522617
// flow-typed version: <<STUB>>/search-index_v0.15.0/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'search-index'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'search-index' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'search-index/dist/search-index' {
  declare module.exports: any;
}

declare module 'search-index/dist/search-index.min' {
  declare module.exports: any;
}

declare module 'search-index/lib/index' {
  declare module.exports: any;
}

declare module 'search-index/lib/siUtil' {
  declare module.exports: any;
}

// Filename aliases
declare module 'search-index/dist/search-index.js' {
  declare module.exports: $Exports<'search-index/dist/search-index'>;
}
declare module 'search-index/dist/search-index.min.js' {
  declare module.exports: $Exports<'search-index/dist/search-index.min'>;
}
declare module 'search-index/lib/index.js' {
  declare module.exports: $Exports<'search-index/lib/index'>;
}
declare module 'search-index/lib/siUtil.js' {
  declare module.exports: $Exports<'search-index/lib/siUtil'>;
}
