// flow-typed signature: e78158e23e97a972a5fae46dabc99780
// flow-typed version: <<STUB>>/xregexp_v4.1.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xregexp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xregexp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xregexp/lib/addons/build' {
  declare module.exports: any;
}

declare module 'xregexp/lib/addons/matchrecursive' {
  declare module.exports: any;
}

declare module 'xregexp/lib/addons/unicode-base' {
  declare module.exports: any;
}

declare module 'xregexp/lib/addons/unicode-blocks' {
  declare module.exports: any;
}

declare module 'xregexp/lib/addons/unicode-categories' {
  declare module.exports: any;
}

declare module 'xregexp/lib/addons/unicode-properties' {
  declare module.exports: any;
}

declare module 'xregexp/lib/addons/unicode-scripts' {
  declare module.exports: any;
}

declare module 'xregexp/lib/index' {
  declare module.exports: any;
}

declare module 'xregexp/lib/xregexp' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/build' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/matchrecursive' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/unicode-base' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/unicode-blocks' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/unicode-categories' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/unicode-properties' {
  declare module.exports: any;
}

declare module 'xregexp/src/addons/unicode-scripts' {
  declare module.exports: any;
}

declare module 'xregexp/src/index' {
  declare module.exports: any;
}

declare module 'xregexp/src/xregexp' {
  declare module.exports: any;
}

declare module 'xregexp/tools/output/blocks' {
  declare module.exports: any;
}

declare module 'xregexp/tools/output/categories' {
  declare module.exports: any;
}

declare module 'xregexp/tools/output/properties' {
  declare module.exports: any;
}

declare module 'xregexp/tools/output/scripts' {
  declare module.exports: any;
}

declare module 'xregexp/tools/scripts/block-regex' {
  declare module.exports: any;
}

declare module 'xregexp/tools/scripts/category-regex' {
  declare module.exports: any;
}

declare module 'xregexp/tools/scripts/property-regex' {
  declare module.exports: any;
}

declare module 'xregexp/tools/scripts/script-regex' {
  declare module.exports: any;
}

declare module 'xregexp/tools/scripts/utils' {
  declare module.exports: any;
}

declare module 'xregexp/xregexp-all' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xregexp/lib/addons/build.js' {
  declare module.exports: $Exports<'xregexp/lib/addons/build'>;
}
declare module 'xregexp/lib/addons/matchrecursive.js' {
  declare module.exports: $Exports<'xregexp/lib/addons/matchrecursive'>;
}
declare module 'xregexp/lib/addons/unicode-base.js' {
  declare module.exports: $Exports<'xregexp/lib/addons/unicode-base'>;
}
declare module 'xregexp/lib/addons/unicode-blocks.js' {
  declare module.exports: $Exports<'xregexp/lib/addons/unicode-blocks'>;
}
declare module 'xregexp/lib/addons/unicode-categories.js' {
  declare module.exports: $Exports<'xregexp/lib/addons/unicode-categories'>;
}
declare module 'xregexp/lib/addons/unicode-properties.js' {
  declare module.exports: $Exports<'xregexp/lib/addons/unicode-properties'>;
}
declare module 'xregexp/lib/addons/unicode-scripts.js' {
  declare module.exports: $Exports<'xregexp/lib/addons/unicode-scripts'>;
}
declare module 'xregexp/lib/index.js' {
  declare module.exports: $Exports<'xregexp/lib/index'>;
}
declare module 'xregexp/lib/xregexp.js' {
  declare module.exports: $Exports<'xregexp/lib/xregexp'>;
}
declare module 'xregexp/src/addons/build.js' {
  declare module.exports: $Exports<'xregexp/src/addons/build'>;
}
declare module 'xregexp/src/addons/matchrecursive.js' {
  declare module.exports: $Exports<'xregexp/src/addons/matchrecursive'>;
}
declare module 'xregexp/src/addons/unicode-base.js' {
  declare module.exports: $Exports<'xregexp/src/addons/unicode-base'>;
}
declare module 'xregexp/src/addons/unicode-blocks.js' {
  declare module.exports: $Exports<'xregexp/src/addons/unicode-blocks'>;
}
declare module 'xregexp/src/addons/unicode-categories.js' {
  declare module.exports: $Exports<'xregexp/src/addons/unicode-categories'>;
}
declare module 'xregexp/src/addons/unicode-properties.js' {
  declare module.exports: $Exports<'xregexp/src/addons/unicode-properties'>;
}
declare module 'xregexp/src/addons/unicode-scripts.js' {
  declare module.exports: $Exports<'xregexp/src/addons/unicode-scripts'>;
}
declare module 'xregexp/src/index.js' {
  declare module.exports: $Exports<'xregexp/src/index'>;
}
declare module 'xregexp/src/xregexp.js' {
  declare module.exports: $Exports<'xregexp/src/xregexp'>;
}
declare module 'xregexp/tools/output/blocks.js' {
  declare module.exports: $Exports<'xregexp/tools/output/blocks'>;
}
declare module 'xregexp/tools/output/categories.js' {
  declare module.exports: $Exports<'xregexp/tools/output/categories'>;
}
declare module 'xregexp/tools/output/properties.js' {
  declare module.exports: $Exports<'xregexp/tools/output/properties'>;
}
declare module 'xregexp/tools/output/scripts.js' {
  declare module.exports: $Exports<'xregexp/tools/output/scripts'>;
}
declare module 'xregexp/tools/scripts/block-regex.js' {
  declare module.exports: $Exports<'xregexp/tools/scripts/block-regex'>;
}
declare module 'xregexp/tools/scripts/category-regex.js' {
  declare module.exports: $Exports<'xregexp/tools/scripts/category-regex'>;
}
declare module 'xregexp/tools/scripts/property-regex.js' {
  declare module.exports: $Exports<'xregexp/tools/scripts/property-regex'>;
}
declare module 'xregexp/tools/scripts/script-regex.js' {
  declare module.exports: $Exports<'xregexp/tools/scripts/script-regex'>;
}
declare module 'xregexp/tools/scripts/utils.js' {
  declare module.exports: $Exports<'xregexp/tools/scripts/utils'>;
}
declare module 'xregexp/xregexp-all.js' {
  declare module.exports: $Exports<'xregexp/xregexp-all'>;
}
