// flow-typed signature: c6dfa923494fec000827d4664e71e920
// flow-typed version: <<STUB>>/@akashaproject/geth-connector_v1.7.30/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@akashaproject/geth-connector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@akashaproject/geth-connector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@akashaproject/geth-connector/lib/Constants' {
  declare module.exports: any;
}

declare module '@akashaproject/geth-connector/lib/GethBin' {
  declare module.exports: any;
}

declare module '@akashaproject/geth-connector/lib/GethConnector' {
  declare module.exports: any;
}

declare module '@akashaproject/geth-connector/lib/GethHelper' {
  declare module.exports: any;
}

declare module '@akashaproject/geth-connector/lib/Web3' {
  declare module.exports: any;
}

// Filename aliases
declare module '@akashaproject/geth-connector/index' {
  declare module.exports: $Exports<'@akashaproject/geth-connector'>;
}
declare module '@akashaproject/geth-connector/index.js' {
  declare module.exports: $Exports<'@akashaproject/geth-connector'>;
}
declare module '@akashaproject/geth-connector/lib/Constants.js' {
  declare module.exports: $Exports<'@akashaproject/geth-connector/lib/Constants'>;
}
declare module '@akashaproject/geth-connector/lib/GethBin.js' {
  declare module.exports: $Exports<'@akashaproject/geth-connector/lib/GethBin'>;
}
declare module '@akashaproject/geth-connector/lib/GethConnector.js' {
  declare module.exports: $Exports<'@akashaproject/geth-connector/lib/GethConnector'>;
}
declare module '@akashaproject/geth-connector/lib/GethHelper.js' {
  declare module.exports: $Exports<'@akashaproject/geth-connector/lib/GethHelper'>;
}
declare module '@akashaproject/geth-connector/lib/Web3.js' {
  declare module.exports: $Exports<'@akashaproject/geth-connector/lib/Web3'>;
}
