export const AUTH_LOGIN = 'AUTH_LOGIN';

export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

export const LOCAL_PROFILES_FOUND = 'LOCAL_PROFILES_FOUND';
export const LOCAL_PROFILES_NONE = 'LOCAL_PROFILES_NONE';
