
export const UPDATE_NAME   = 'UPDATE_NAME';
export const VALID_NAME    = 'VALID_NAME';

export const UPDATE_USER   = 'UPDATE_USER';
export const VALID_USER    = 'VALID_USER';

export const UPDATE_PASSWD = 'UPDATE_PASSWD';
export const VALID_PASSWD  = 'VALID_PASSWD';

export const TOGGLE_DETAILS = 'TOGGLE_DETAILS';
export const UNLOCK_ENABLE  = 'UNLOCK_ENABLE';
export const UNLOCK_ACCOUNT_FOR = 'UNLOCK_ACCOUNT_FOR';
export const CREATE_ETH_ADDRESS = 'CREATE_ETH_ADDRESS';

export const CREATE_USER_PENDING = 'CREATE_USER_PENDING';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';
