
export const UPDATE_NAME = 'UPDATE_NAME';
export const VALID_NAME = 'VALID_NAME';

export const UPDATE_USER = 'UPDATE_USER';
export const VALID_USERNAME = 'VALID_USER';

export const UPDATE_PASSWD = 'UPDATE_PASSWD';
export const VALID_PASSWD = 'VALID_PASSWD';

export const TOGGLE_DETAILS = 'TOGGLE_DETAILS';
export const UNLOCK_ENABLE = 'UNLOCK_ENABLE';
export const UNLOCK_ACCOUNT_FOR = 'UNLOCK_ACCOUNT_FOR';
export const CREATE_ETH_ADDRESS = 'CREATE_ETH_ADDRESS';

export const CREATE_PROFILE_PENDING = 'CREATE_USER_PENDING';
export const CREATE_PROFILE_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_PROFILE_FAILURE = 'CREATE_USER_FAILURE';

export const AUTH_LOGIN = 'AUTH_LOGIN';

export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';

export const LOCAL_PROFILES_FOUND = 'LOCAL_PROFILES_FOUND';
export const LOCAL_PROFILES_NONE = 'LOCAL_PROFILES_NONE';

export const GET_PROFILES_LIST_SUCCESS = 'GET_PROFILES_LIST_SUCCESS';
export const GET_PROFILES_LIST_ERROR = 'GET_PROFILES_LIST_ERROR';
