export const UPDATE_NAME   = 'UPDATE_NAME';
export const UPDATE_USER   = 'UPDATE_USER';
export const UPDATE_PASSWD = 'UPDATE_PASSWD';

export const TOGGLE_DETAILS = 'TOGGLE_DETAILS';

export const CHECK_CREATE = 'CHECK_CREATE';
export const CHECK_CREATE_SUCCESS = 'CHECK_CREATE_SUCCESS';
export const CHECK_CREATE_FAILURE = 'CHECK_CREATE_FAILURE';
