// geth
export const START_GETH_SUCCESS = 'START_GETH_SUCCESS';
export const START_GETH_ERROR = 'START_GETH_ERROR';
export const STOP_GETH_SUCCESS = 'STOP_GETH_SUCCESS';
export const STOP_GETH_ERROR = 'STOP_GETH_ERROR';
// ipfs
export const START_IPFS_SUCCESS = 'START_IPFS_SUCCESS';
export const START_IPFS_ERROR = 'START_IPFS_ERROR';
export const STOP_IPFS_SUCCESS = 'STOP_IPFS_SUCCESS';
export const STOP_IPFS_ERROR = 'STOP_IPFS_ERROR';
