export const SETUP_GETH   = 'SETUP_GETH';
export const SETUP_IPFS   = 'SETUP_IPFS';
export const SET_GETH_IPC = 'SET_GETH_IPC';

export const TOGGLE_ADVANCED = 'TOGGLE_ADVANCED';
export const DEFAULT_OPTIONS = 'DEFAULT_OPTIONS';

export const SUBMIT_OPTIONS = 'SUBMIT_OPTIONS';

export const START_GETH = 'START_GETH';
export const START_GETH_FAILURE = 'START_GETH_FAILURE';
